package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	beyondcorpservice "github.com/BishopFox/cloudfox/gcp/services/beyondcorpService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPBeyondCorpCommand = &cobra.Command{
	Use:     globals.GCP_BEYONDCORP_MODULE_NAME,
	Aliases: []string{"bc", "zero-trust"},
	Short:   "Enumerate BeyondCorp Enterprise configurations",
	Long: `Enumerate BeyondCorp Enterprise configurations.

Features:
- Lists app connectors and connections
- Analyzes connection endpoints
- Identifies configuration issues`,
	Run: runGCPBeyondCorpCommand,
}

type BeyondCorpModule struct {
	gcpinternal.BaseGCPModule
	AppConnectors  []beyondcorpservice.AppConnectorInfo
	AppConnections []beyondcorpservice.AppConnectionInfo
	LootMap        map[string]*internal.LootFile
	mu             sync.Mutex
}

type BeyondCorpOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o BeyondCorpOutput) TableFiles() []internal.TableFile { return o.Table }
func (o BeyondCorpOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPBeyondCorpCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_BEYONDCORP_MODULE_NAME)
	if err != nil {
		return
	}

	module := &BeyondCorpModule{
		BaseGCPModule:  gcpinternal.NewBaseGCPModule(cmdCtx),
		AppConnectors:  []beyondcorpservice.AppConnectorInfo{},
		AppConnections: []beyondcorpservice.AppConnectionInfo{},
		LootMap:        make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *BeyondCorpModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_BEYONDCORP_MODULE_NAME, m.processProject)

	totalCount := len(m.AppConnectors) + len(m.AppConnections)
	if totalCount == 0 {
		logger.InfoM("No BeyondCorp resources found", globals.GCP_BEYONDCORP_MODULE_NAME)
		return
	}

	// Count public resources
	publicConnectorCount := 0
	publicConnectionCount := 0
	for _, connector := range m.AppConnectors {
		if connector.PublicAccess {
			publicConnectorCount++
		}
	}
	for _, conn := range m.AppConnections {
		if conn.PublicAccess {
			publicConnectionCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d connector(s), %d connection(s)",
		len(m.AppConnectors), len(m.AppConnections)),
		globals.GCP_BEYONDCORP_MODULE_NAME)

	if publicConnectorCount > 0 || publicConnectionCount > 0 {
		logger.InfoM(fmt.Sprintf("[FINDING] Found %d public connector(s), %d public connection(s)!",
			publicConnectorCount, publicConnectionCount), globals.GCP_BEYONDCORP_MODULE_NAME)
	}

	m.writeOutput(ctx, logger)
}

func (m *BeyondCorpModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating BeyondCorp in project: %s", projectID), globals.GCP_BEYONDCORP_MODULE_NAME)
	}

	svc := beyondcorpservice.New()

	// Get app connectors
	connectors, _ := svc.ListAppConnectors(projectID)
	m.mu.Lock()
	m.AppConnectors = append(m.AppConnectors, connectors...)
	m.mu.Unlock()

	// Get app connections
	connections, _ := svc.ListAppConnections(projectID)
	m.mu.Lock()
	m.AppConnections = append(m.AppConnections, connections...)
	m.mu.Unlock()

	m.mu.Lock()
	for _, conn := range connections {
		m.addConnectionToLoot(conn)
	}
	m.mu.Unlock()
}

func (m *BeyondCorpModule) initializeLootFiles() {
	m.LootMap["beyondcorp-details"] = &internal.LootFile{
		Name:     "beyondcorp-details",
		Contents: "# BeyondCorp Details\n# Generated by CloudFox\n\n",
	}
}

func (m *BeyondCorpModule) addConnectionToLoot(conn beyondcorpservice.AppConnectionInfo) {
	m.LootMap["beyondcorp-details"].Contents += fmt.Sprintf(
		"# Connection: %s\n# Endpoint: %s\n# Gateway: %s\n# Connectors: %s\n",
		conn.Name, conn.ApplicationEndpoint, conn.Gateway, strings.Join(conn.Connectors, ", "))

	if conn.ApplicationEndpoint != "" {
		m.LootMap["beyondcorp-details"].Contents += fmt.Sprintf("# Application Endpoint: %s\n", conn.ApplicationEndpoint)
	}
	m.LootMap["beyondcorp-details"].Contents += "\n"
}

func (m *BeyondCorpModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// App Connectors table (one row per IAM binding member)
	if len(m.AppConnectors) > 0 {
		header := []string{"Project Name", "Project ID", "Name", "Location", "State", "Service Account", "Role", "Member", "Public"}
		var body [][]string
		for _, connector := range m.AppConnectors {
			publicAccess := "No"
			if connector.PublicAccess {
				publicAccess = "Yes"
			}

			// If no IAM bindings, still show the connector
			if len(connector.IAMBindings) == 0 {
				body = append(body, []string{
					m.GetProjectName(connector.ProjectID),
					connector.ProjectID,
					connector.Name,
					connector.Location,
					connector.State,
					connector.PrincipalInfo,
					"-",
					"-",
					publicAccess,
				})
			} else {
				// One row per member per role
				for _, binding := range connector.IAMBindings {
					for _, member := range binding.Members {
						body = append(body, []string{
							m.GetProjectName(connector.ProjectID),
							connector.ProjectID,
							connector.Name,
							connector.Location,
							connector.State,
							connector.PrincipalInfo,
							binding.Role,
							member,
							publicAccess,
						})
					}
				}
			}
		}
		tables = append(tables, internal.TableFile{
			Name:   "beyondcorp-connectors",
			Header: header,
			Body:   body,
		})
	}

	// App Connections table (one row per IAM binding member)
	if len(m.AppConnections) > 0 {
		header := []string{"Project Name", "Project ID", "Name", "Location", "State", "Endpoint", "Gateway", "Role", "Member", "Public"}
		var body [][]string
		for _, conn := range m.AppConnections {
			publicAccess := "No"
			if conn.PublicAccess {
				publicAccess = "Yes"
			}

			// If no IAM bindings, still show the connection
			if len(conn.IAMBindings) == 0 {
				body = append(body, []string{
					m.GetProjectName(conn.ProjectID),
					conn.ProjectID,
					conn.Name,
					conn.Location,
					conn.State,
					conn.ApplicationEndpoint,
					conn.Gateway,
					"-",
					"-",
					publicAccess,
				})
			} else {
				// One row per member per role
				for _, binding := range conn.IAMBindings {
					for _, member := range binding.Members {
						body = append(body, []string{
							m.GetProjectName(conn.ProjectID),
							conn.ProjectID,
							conn.Name,
							conn.Location,
							conn.State,
							conn.ApplicationEndpoint,
							conn.Gateway,
							binding.Role,
							member,
							publicAccess,
						})
					}
				}
			}
		}
		tables = append(tables, internal.TableFile{
			Name:   "beyondcorp-connections",
			Header: header,
			Body:   body,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := BeyondCorpOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_BEYONDCORP_MODULE_NAME)
	}
}
