package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	bigtableservice "github.com/BishopFox/cloudfox/gcp/services/bigtableService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPBigtableCommand = &cobra.Command{
	Use:     globals.GCP_BIGTABLE_MODULE_NAME,
	Aliases: []string{"bt"},
	Short:   "Enumerate Cloud Bigtable instances and tables",
	Long: `Enumerate Cloud Bigtable instances, clusters, and tables with IAM analysis.

Features:
- Lists all Bigtable instances with instance-level IAM bindings
- Lists all tables with table-level IAM bindings
- Identifies publicly accessible instances and tables
- Shows cluster information per instance`,
	Run: runGCPBigtableCommand,
}

type BigtableModule struct {
	gcpinternal.BaseGCPModule
	Instances []bigtableservice.BigtableInstanceInfo
	Tables    []bigtableservice.BigtableTableInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

type BigtableOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o BigtableOutput) TableFiles() []internal.TableFile { return o.Table }
func (o BigtableOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPBigtableCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_BIGTABLE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &BigtableModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Instances:     []bigtableservice.BigtableInstanceInfo{},
		Tables:        []bigtableservice.BigtableTableInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *BigtableModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_BIGTABLE_MODULE_NAME, m.processProject)

	if len(m.Instances) == 0 {
		logger.InfoM("No Bigtable instances found", globals.GCP_BIGTABLE_MODULE_NAME)
		return
	}

	// Count public instances and tables
	publicInstanceCount := 0
	publicTableCount := 0
	for _, instance := range m.Instances {
		if instance.PublicAccess {
			publicInstanceCount++
		}
	}
	for _, table := range m.Tables {
		if table.PublicAccess {
			publicTableCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d instance(s) with %d table(s)",
		len(m.Instances), len(m.Tables)), globals.GCP_BIGTABLE_MODULE_NAME)

	if publicInstanceCount > 0 || publicTableCount > 0 {
		logger.InfoM(fmt.Sprintf("[FINDING] Found %d public instance(s), %d public table(s)!",
			publicInstanceCount, publicTableCount), globals.GCP_BIGTABLE_MODULE_NAME)
	}

	m.writeOutput(ctx, logger)
}

func (m *BigtableModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Bigtable in project: %s", projectID), globals.GCP_BIGTABLE_MODULE_NAME)
	}

	svc := bigtableservice.New()
	result, err := svc.ListInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_BIGTABLE_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Bigtable instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Instances = append(m.Instances, result.Instances...)
	m.Tables = append(m.Tables, result.Tables...)
	for _, instance := range result.Instances {
		m.addInstanceToLoot(instance)
	}
	for _, table := range result.Tables {
		m.addTableToLoot(table)
	}
	m.mu.Unlock()
}

func (m *BigtableModule) initializeLootFiles() {
	m.LootMap["bigtable-commands"] = &internal.LootFile{
		Name:     "bigtable-commands",
		Contents: "# Bigtable Commands\n# Generated by CloudFox\n\n",
	}
}

func (m *BigtableModule) addInstanceToLoot(instance bigtableservice.BigtableInstanceInfo) {
	var clusterNames []string
	for _, cluster := range instance.Clusters {
		clusterNames = append(clusterNames, cluster.Name)
	}

	m.LootMap["bigtable-commands"].Contents += fmt.Sprintf(
		"# Instance: %s (%s)\n"+
			"# Type: %s, State: %s\n"+
			"# Clusters: %s\n"+
			"cbt -project %s -instance %s ls\n\n",
		instance.Name, instance.DisplayName,
		instance.Type, instance.State,
		strings.Join(clusterNames, ", "),
		instance.ProjectID, instance.Name,
	)
}

func (m *BigtableModule) addTableToLoot(table bigtableservice.BigtableTableInfo) {
	m.LootMap["bigtable-commands"].Contents += fmt.Sprintf(
		"# Table: %s (Instance: %s)\n"+
			"cbt -project %s -instance %s read %s count=10\n\n",
		table.Name, table.InstanceName,
		table.ProjectID, table.InstanceName, table.Name,
	)
}

func (m *BigtableModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Instances table (one row per IAM binding member)
	instanceHeader := []string{"Project Name", "Project ID", "Instance", "Display Name", "Type", "State", "Clusters", "Role", "Member", "Public"}

	var instanceBody [][]string
	for _, instance := range m.Instances {
		publicAccess := "No"
		if instance.PublicAccess {
			publicAccess = "Yes"
		}

		// Build cluster info string: "name (location)" for each cluster
		var clusterDetails []string
		for _, cluster := range instance.Clusters {
			clusterDetails = append(clusterDetails, fmt.Sprintf("%s (%s)", cluster.Name, cluster.Location))
		}
		clusters := "-"
		if len(clusterDetails) > 0 {
			clusters = strings.Join(clusterDetails, ", ")
		}

		// If no IAM bindings, still show the instance
		if len(instance.IAMBindings) == 0 {
			instanceBody = append(instanceBody, []string{
				m.GetProjectName(instance.ProjectID),
				instance.ProjectID,
				instance.Name,
				instance.DisplayName,
				instance.Type,
				instance.State,
				clusters,
				"-",
				"-",
				publicAccess,
			})
		} else {
			// One row per member per role
			for _, binding := range instance.IAMBindings {
				for _, member := range binding.Members {
					instanceBody = append(instanceBody, []string{
						m.GetProjectName(instance.ProjectID),
						instance.ProjectID,
						instance.Name,
						instance.DisplayName,
						instance.Type,
						instance.State,
						clusters,
						binding.Role,
						member,
						publicAccess,
					})
				}
			}
		}
	}

	if len(instanceBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "bigtable-instances",
			Header: instanceHeader,
			Body:   instanceBody,
		})
	}

	// Tables table (one row per IAM binding member)
	tableHeader := []string{"Project Name", "Project ID", "Instance", "Table", "Role", "Member", "Public"}

	var tableBody [][]string
	for _, table := range m.Tables {
		publicAccess := "No"
		if table.PublicAccess {
			publicAccess = "Yes"
		}

		// If no IAM bindings, still show the table
		if len(table.IAMBindings) == 0 {
			tableBody = append(tableBody, []string{
				m.GetProjectName(table.ProjectID),
				table.ProjectID,
				table.InstanceName,
				table.Name,
				"-",
				"-",
				publicAccess,
			})
		} else {
			// One row per member per role
			for _, binding := range table.IAMBindings {
				for _, member := range binding.Members {
					tableBody = append(tableBody, []string{
						m.GetProjectName(table.ProjectID),
						table.ProjectID,
						table.InstanceName,
						table.Name,
						binding.Role,
						member,
						publicAccess,
					})
				}
			}
		}
	}

	if len(tableBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "bigtable-tables",
			Header: tableHeader,
			Body:   tableBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := BigtableOutput{
		Table: tables,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
}
