package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	cloudbuildservice "github.com/BishopFox/cloudfox/gcp/services/cloudbuildService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPCloudBuildCommand = &cobra.Command{
	Use:     globals.GCP_CLOUDBUILD_MODULE_NAME,
	Aliases: []string{"cb", "build", "builds"},
	Short:   "Enumerate Cloud Build triggers and builds",
	Long: `Enumerate Cloud Build triggers and recent build executions.

Features:
- Lists all build triggers
- Shows trigger source configuration (GitHub, CSR)
- Identifies service accounts used for builds
- Shows recent build executions
- Detects potentially risky trigger configurations`,
	Run: runGCPCloudBuildCommand,
}

// ------------------------------
// Module Struct with embedded BaseGCPModule
// ------------------------------
type CloudBuildModule struct {
	gcpinternal.BaseGCPModule

	// Module-specific fields
	Triggers         []cloudbuildservice.TriggerInfo
	Builds           []cloudbuildservice.BuildInfo
	SecurityAnalysis []cloudbuildservice.TriggerSecurityAnalysis
	LootMap          map[string]*internal.LootFile
	mu               sync.Mutex
}

// ------------------------------
// Output Struct implementing CloudfoxOutput interface
// ------------------------------
type CloudBuildOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o CloudBuildOutput) TableFiles() []internal.TableFile { return o.Table }
func (o CloudBuildOutput) LootFiles() []internal.LootFile   { return o.Loot }

// ------------------------------
// Command Entry Point
// ------------------------------
func runGCPCloudBuildCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_CLOUDBUILD_MODULE_NAME)
	if err != nil {
		return
	}

	module := &CloudBuildModule{
		BaseGCPModule:    gcpinternal.NewBaseGCPModule(cmdCtx),
		Triggers:         []cloudbuildservice.TriggerInfo{},
		Builds:           []cloudbuildservice.BuildInfo{},
		SecurityAnalysis: []cloudbuildservice.TriggerSecurityAnalysis{},
		LootMap:          make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

// ------------------------------
// Module Execution
// ------------------------------
func (m *CloudBuildModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_CLOUDBUILD_MODULE_NAME, m.processProject)

	if len(m.Triggers) == 0 && len(m.Builds) == 0 {
		logger.InfoM("No Cloud Build triggers or builds found", globals.GCP_CLOUDBUILD_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d trigger(s), %d recent build(s)",
		len(m.Triggers), len(m.Builds)), globals.GCP_CLOUDBUILD_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

// ------------------------------
// Project Processor
// ------------------------------
func (m *CloudBuildModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Cloud Build in project: %s", projectID), globals.GCP_CLOUDBUILD_MODULE_NAME)
	}

	cbSvc := cloudbuildservice.New()

	// Get triggers
	triggers, err := cbSvc.ListTriggers(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_CLOUDBUILD_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Cloud Build triggers in project %s", projectID))
	}

	// Get recent builds
	builds, err := cbSvc.ListBuilds(projectID, 20)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_CLOUDBUILD_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Cloud Build builds in project %s", projectID))
	}

	m.mu.Lock()
	m.Triggers = append(m.Triggers, triggers...)
	m.Builds = append(m.Builds, builds...)

	for _, trigger := range triggers {
		m.addTriggerToLoot(trigger)
		// Perform security analysis
		analysis := cbSvc.AnalyzeTriggerForPrivesc(trigger, projectID)
		m.SecurityAnalysis = append(m.SecurityAnalysis, analysis)
		m.addSecurityAnalysisToLoot(analysis)
	}

	// Add build step analysis to loot
	for _, build := range builds {
		m.addBuildToLoot(build)
	}
	m.mu.Unlock()
}

// ------------------------------
// Loot File Management
// ------------------------------
func (m *CloudBuildModule) initializeLootFiles() {
	m.LootMap["cloudbuild-details"] = &internal.LootFile{
		Name:     "cloudbuild-details",
		Contents: "# Cloud Build Details\n# Generated by CloudFox\n\n",
	}
}

func (m *CloudBuildModule) addTriggerToLoot(trigger cloudbuildservice.TriggerInfo) {
	// Build flags for special attributes
	var flags []string
	if trigger.PrivescPotential {
		flags = append(flags, "PRIVESC POTENTIAL")
	}
	if trigger.Disabled {
		flags = append(flags, "DISABLED")
	}

	flagStr := ""
	if len(flags) > 0 {
		flagStr = " [" + strings.Join(flags, "] [") + "]"
	}

	sa := trigger.ServiceAccount
	if sa == "" {
		sa = "(default)"
	}

	branchTag := trigger.BranchName
	if branchTag == "" {
		branchTag = trigger.TagName
	}

	m.LootMap["cloudbuild-details"].Contents += fmt.Sprintf(
		"# %s (%s)%s\n"+
			"Project: %s\n"+
			"Source: %s - %s\n"+
			"Branch/Tag: %s | Config: %s\n"+
			"Service Account: %s\n",
		trigger.Name, trigger.ID, flagStr,
		trigger.ProjectID,
		trigger.SourceType, trigger.RepoName,
		branchTag, trigger.Filename,
		sa,
	)
}

func (m *CloudBuildModule) addSecurityAnalysisToLoot(analysis cloudbuildservice.TriggerSecurityAnalysis) {
	// Add exploitation commands if available
	if len(analysis.ExploitCommands) > 0 {
		m.LootMap["cloudbuild-details"].Contents += "Exploitation:\n"
		for _, cmd := range analysis.ExploitCommands {
			m.LootMap["cloudbuild-details"].Contents += fmt.Sprintf("  %s\n", cmd)
		}
	}
	m.LootMap["cloudbuild-details"].Contents += "\n"
}

func (m *CloudBuildModule) addBuildToLoot(build cloudbuildservice.BuildInfo) {
	buildID := build.ID
	if len(buildID) > 12 {
		buildID = buildID[:12]
	}

	m.LootMap["cloudbuild-details"].Contents += fmt.Sprintf(
		"# Build: %s\n"+
			"Project: %s | Status: %s\n"+
			"Trigger: %s | Source: %s\n",
		buildID,
		build.ProjectID, build.Status,
		build.TriggerID, build.Source,
	)

	// Log location
	if build.LogsBucket != "" {
		m.LootMap["cloudbuild-details"].Contents += fmt.Sprintf(
			"Logs: gsutil cat %s/log-%s.txt\n",
			build.LogsBucket, build.ID,
		)
	}

	// Secret environment variables
	if len(build.SecretEnvVars) > 0 {
		m.LootMap["cloudbuild-details"].Contents += "Secret Env Vars:\n"
		for _, secret := range build.SecretEnvVars {
			m.LootMap["cloudbuild-details"].Contents += fmt.Sprintf("  - %s\n", secret)
		}
	}

	m.LootMap["cloudbuild-details"].Contents += "\n"
}

// ------------------------------
// Output Generation
// ------------------------------
func (m *CloudBuildModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Triggers table
	triggersHeader := []string{
		"Project Name",
		"Project ID",
		"Name",
		"Source",
		"Repository",
		"Branch/Tag",
		"Config File",
		"Service Account",
		"Disabled",
		"Privesc Potential",
	}

	var triggersBody [][]string
	privescCount := 0
	for _, trigger := range m.Triggers {
		disabled := "No"
		if trigger.Disabled {
			disabled = "Yes"
		}

		privesc := "No"
		if trigger.PrivescPotential {
			privesc = "Yes"
			privescCount++
		}

		branchTag := trigger.BranchName
		if branchTag == "" {
			branchTag = trigger.TagName
		}

		sa := trigger.ServiceAccount
		if sa == "" {
			sa = "(default)"
		}

		triggersBody = append(triggersBody, []string{
			m.GetProjectName(trigger.ProjectID),
			trigger.ProjectID,
			trigger.Name,
			trigger.SourceType,
			trigger.RepoName,
			branchTag,
			trigger.Filename,
			sa,
			disabled,
			privesc,
		})
	}

	// Builds table
	buildsHeader := []string{
		"Project Name",
		"Project ID",
		"ID",
		"Status",
		"Trigger",
		"Source",
		"Created",
	}

	var buildsBody [][]string
	for _, build := range m.Builds {
		buildID := build.ID
		if len(buildID) > 12 {
			buildID = buildID[:12]
		}
		buildsBody = append(buildsBody, []string{
			m.GetProjectName(build.ProjectID),
			build.ProjectID,
			buildID,
			build.Status,
			build.TriggerID,
			build.Source,
			build.CreateTime,
		})
	}

	// Collect loot files
	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	var tables []internal.TableFile

	if len(triggersBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "cloudbuild-triggers",
			Header: triggersHeader,
			Body:   triggersBody,
		})
	}

	if len(buildsBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "cloudbuild-builds",
			Header: buildsHeader,
			Body:   buildsBody,
		})
	}

	if privescCount > 0 {
		logger.InfoM(fmt.Sprintf("[PENTEST] Found %d trigger(s) with privilege escalation potential!", privescCount), globals.GCP_CLOUDBUILD_MODULE_NAME)
	}

	output := CloudBuildOutput{
		Table: tables,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart(
		"gcp",
		m.Format,
		m.OutputDirectory,
		m.Verbosity,
		m.WrapTable,
		"project",
		m.ProjectIDs,
		scopeNames,
		m.Account,
		output,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_CLOUDBUILD_MODULE_NAME)
		m.CommandCounter.Error++
	}
}
