package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	composerservice "github.com/BishopFox/cloudfox/gcp/services/composerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPComposerCommand = &cobra.Command{
	Use:     globals.GCP_COMPOSER_MODULE_NAME,
	Aliases: []string{"airflow"},
	Short:   "Enumerate Cloud Composer environments",
	Long: `Enumerate Cloud Composer (managed Apache Airflow) environments.

Features:
- Lists all Composer environments across locations
- Shows Airflow web UI endpoints
- Identifies service account configuration
- Analyzes network exposure (private vs public)
- Detects overly permissive IP restrictions`,
	Run: runGCPComposerCommand,
}

type ComposerModule struct {
	gcpinternal.BaseGCPModule
	Environments []composerservice.EnvironmentInfo
	LootMap      map[string]*internal.LootFile
	mu           sync.Mutex
}

type ComposerOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o ComposerOutput) TableFiles() []internal.TableFile { return o.Table }
func (o ComposerOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPComposerCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_COMPOSER_MODULE_NAME)
	if err != nil {
		return
	}

	module := &ComposerModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Environments:  []composerservice.EnvironmentInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *ComposerModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_COMPOSER_MODULE_NAME, m.processProject)

	if len(m.Environments) == 0 {
		logger.InfoM("No Composer environments found", globals.GCP_COMPOSER_MODULE_NAME)
		return
	}

	// Count by state
	running := 0
	publicEnvs := 0
	for _, env := range m.Environments {
		if env.State == "RUNNING" {
			running++
		}
		if !env.PrivateEnvironment {
			publicEnvs++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d Composer environment(s) (%d running, %d public)",
		len(m.Environments), running, publicEnvs), globals.GCP_COMPOSER_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *ComposerModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Composer in project: %s", projectID), globals.GCP_COMPOSER_MODULE_NAME)
	}

	svc := composerservice.New()
	environments, err := svc.ListEnvironments(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_COMPOSER_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Composer environments in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Environments = append(m.Environments, environments...)
	for _, env := range environments {
		m.addToLoot(env)
	}
	m.mu.Unlock()
}

func (m *ComposerModule) initializeLootFiles() {
	m.LootMap["composer-commands"] = &internal.LootFile{
		Name:     "composer-commands",
		Contents: "# Composer Commands\n# Generated by CloudFox\n\n",
	}
}

func (m *ComposerModule) addToLoot(env composerservice.EnvironmentInfo) {
	m.LootMap["composer-commands"].Contents += fmt.Sprintf(
		"# %s (%s)\n"+
			"# Project: %s\n",
		env.Name, env.Location,
		env.ProjectID,
	)

	// gcloud commands
	m.LootMap["composer-commands"].Contents += fmt.Sprintf(
		"gcloud composer environments describe %s --location=%s --project=%s\n"+
			"gcloud composer environments run %s --location=%s --project=%s dags list\n",
		env.Name, env.Location, env.ProjectID,
		env.Name, env.Location, env.ProjectID,
	)

	// DAG bucket command
	if env.DagGcsPrefix != "" {
		m.LootMap["composer-commands"].Contents += fmt.Sprintf(
			"gsutil ls %s\n",
			env.DagGcsPrefix,
		)
	}

	// Airflow Web UI
	if env.AirflowURI != "" {
		m.LootMap["composer-commands"].Contents += fmt.Sprintf(
			"# Airflow Web UI: %s\n",
			env.AirflowURI,
		)
	}

	m.LootMap["composer-commands"].Contents += "\n"
}

func (m *ComposerModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Project Name",
		"Project ID",
		"Name",
		"Location",
		"State",
		"Service Account",
		"Private",
		"Private Endpoint",
		"Airflow URI",
		"DAG Bucket",
		"Image Version",
	}

	var body [][]string
	for _, env := range m.Environments {
		sa := env.ServiceAccount
		if sa == "" {
			sa = "(default)"
		}

		airflowURI := env.AirflowURI
		if airflowURI == "" {
			airflowURI = "-"
		}

		dagBucket := env.DagGcsPrefix
		if dagBucket == "" {
			dagBucket = "-"
		}

		imageVersion := env.ImageVersion
		if imageVersion == "" {
			imageVersion = "-"
		}

		body = append(body, []string{
			m.GetProjectName(env.ProjectID),
			env.ProjectID,
			env.Name,
			env.Location,
			env.State,
			sa,
			boolToYesNo(env.PrivateEnvironment),
			boolToYesNo(env.EnablePrivateEndpoint),
			airflowURI,
			dagBucket,
			imageVersion,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	tables := []internal.TableFile{{Name: "composer", Header: header, Body: body}}

	output := ComposerOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_COMPOSER_MODULE_NAME)
	}
}
