package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	filestoreservice "github.com/BishopFox/cloudfox/gcp/services/filestoreService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPFilestoreCommand = &cobra.Command{
	Use:     globals.GCP_FILESTORE_MODULE_NAME,
	Aliases: []string{"nfs", "files"},
	Short:   "Enumerate Filestore NFS instances",
	Long:    `Enumerate Filestore instances and their file shares.`,
	Run:     runGCPFilestoreCommand,
}

type FilestoreModule struct {
	gcpinternal.BaseGCPModule
	Instances []filestoreservice.FilestoreInstanceInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

type FilestoreOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o FilestoreOutput) TableFiles() []internal.TableFile { return o.Table }
func (o FilestoreOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPFilestoreCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_FILESTORE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &FilestoreModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Instances:     []filestoreservice.FilestoreInstanceInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *FilestoreModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_FILESTORE_MODULE_NAME, m.processProject)

	if len(m.Instances) == 0 {
		logger.InfoM("No Filestore instances found", globals.GCP_FILESTORE_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d Filestore instance(s)", len(m.Instances)), globals.GCP_FILESTORE_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *FilestoreModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	svc := filestoreservice.New()
	instances, err := svc.ListInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_FILESTORE_MODULE_NAME,
			fmt.Sprintf("Could not enumerate Filestore instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Instances = append(m.Instances, instances...)
	for _, instance := range instances {
		m.addToLoot(instance)
	}
	m.mu.Unlock()
}

func (m *FilestoreModule) initializeLootFiles() {
	m.LootMap["filestore-commands"] = &internal.LootFile{
		Name:     "filestore-commands",
		Contents: "# Filestore Commands\n# Generated by CloudFox\n\n",
	}
}

func (m *FilestoreModule) addToLoot(instance filestoreservice.FilestoreInstanceInfo) {
	m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
		"# %s (%s)\n"+
			"# Project: %s\n",
		instance.Name, instance.Location,
		instance.ProjectID,
	)

	// gcloud command
	m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
		"gcloud filestore instances describe %s --location=%s --project=%s\n",
		instance.Name, instance.Location, instance.ProjectID,
	)

	// Mount commands for each share
	if len(instance.Shares) > 0 && len(instance.IPAddresses) > 0 {
		m.LootMap["filestore-commands"].Contents += "# Mount commands:\n"
		for _, share := range instance.Shares {
			for _, ip := range instance.IPAddresses {
				m.LootMap["filestore-commands"].Contents += fmt.Sprintf(
					"# Share: %s (%dGB)\n"+
						"mount -t nfs %s:/%s /mnt/%s\n",
					share.Name, share.CapacityGB,
					ip, share.Name, share.Name,
				)
			}
		}
	}

	m.LootMap["filestore-commands"].Contents += "\n"
}

func (m *FilestoreModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Project Name",
		"Project ID",
		"Name",
		"Location",
		"Tier",
		"Network",
		"IP",
		"Shares",
		"State",
	}

	var body [][]string
	for _, instance := range m.Instances {
		var shareNames []string
		for _, share := range instance.Shares {
			shareNames = append(shareNames, share.Name)
		}

		ip := strings.Join(instance.IPAddresses, ", ")
		if ip == "" {
			ip = "-"
		}

		shares := strings.Join(shareNames, ", ")
		if shares == "" {
			shares = "-"
		}

		network := instance.Network
		if network == "" {
			network = "-"
		}

		body = append(body, []string{
			m.GetProjectName(instance.ProjectID),
			instance.ProjectID,
			instance.Name,
			instance.Location,
			instance.Tier,
			network,
			ip,
			shares,
			instance.State,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := FilestoreOutput{
		Table: []internal.TableFile{{Name: "filestore", Header: header, Body: body}},
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
}
