package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	FunctionsService "github.com/BishopFox/cloudfox/gcp/services/functionsService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPFunctionsCommand = &cobra.Command{
	Use:     globals.GCP_FUNCTIONS_MODULE_NAME,
	Aliases: []string{"function", "gcf", "cloud-functions"},
	Short:   "Enumerate GCP Cloud Functions with security analysis",
	Long: `Enumerate GCP Cloud Functions across projects with security-relevant details.

Features:
- Lists all Cloud Functions (Gen 2) accessible to the authenticated user
- Shows security configuration (ingress settings, VPC connector, service account)
- Identifies publicly invokable functions (allUsers/allAuthenticatedUsers)
- Shows runtime, trigger type, and trigger configuration
- Counts environment variables and secret references
- Generates gcloud commands for further enumeration and exploitation

Security Columns:
- Ingress: ALL_TRAFFIC (public), INTERNAL_ONLY, or INTERNAL_AND_GCLB
- Public: Whether allUsers or allAuthenticatedUsers can invoke the function
- ServiceAccount: The identity the function runs as (privilege level)
- VPCConnector: Network connectivity to VPC resources
- Secrets: Count of secret environment variables and volumes

Attack Surface:
- Public HTTP functions may be directly exploitable
- Functions with default service account may have excessive permissions
- Functions with VPC connectors can access internal resources
- Event triggers reveal integration points (Pub/Sub, Storage, etc.)`,
	Run: runGCPFunctionsCommand,
}

// ------------------------------
// Module Struct
// ------------------------------
type FunctionsModule struct {
	gcpinternal.BaseGCPModule

	Functions []FunctionsService.FunctionInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

// ------------------------------
// Output Struct
// ------------------------------
type FunctionsOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o FunctionsOutput) TableFiles() []internal.TableFile { return o.Table }
func (o FunctionsOutput) LootFiles() []internal.LootFile   { return o.Loot }

// ------------------------------
// Command Entry Point
// ------------------------------
func runGCPFunctionsCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_FUNCTIONS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &FunctionsModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Functions:     []FunctionsService.FunctionInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

// ------------------------------
// Module Execution
// ------------------------------
func (m *FunctionsModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_FUNCTIONS_MODULE_NAME, m.processProject)

	if len(m.Functions) == 0 {
		logger.InfoM("No Cloud Functions found", globals.GCP_FUNCTIONS_MODULE_NAME)
		return
	}

	// Count public functions
	publicCount := 0
	for _, fn := range m.Functions {
		if fn.IsPublic {
			publicCount++
		}
	}

	if publicCount > 0 {
		logger.SuccessM(fmt.Sprintf("Found %d function(s), %d PUBLIC", len(m.Functions), publicCount), globals.GCP_FUNCTIONS_MODULE_NAME)
	} else {
		logger.SuccessM(fmt.Sprintf("Found %d function(s)", len(m.Functions)), globals.GCP_FUNCTIONS_MODULE_NAME)
	}

	m.writeOutput(ctx, logger)
}

// ------------------------------
// Project Processor
// ------------------------------
func (m *FunctionsModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Cloud Functions in project: %s", projectID), globals.GCP_FUNCTIONS_MODULE_NAME)
	}

	fs := FunctionsService.New()
	functions, err := fs.Functions(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_FUNCTIONS_MODULE_NAME,
			fmt.Sprintf("Could not enumerate functions in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Functions = append(m.Functions, functions...)

	for _, fn := range functions {
		m.addFunctionToLoot(fn)
	}
	m.mu.Unlock()

	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Found %d function(s) in project %s", len(functions), projectID), globals.GCP_FUNCTIONS_MODULE_NAME)
	}
}

// ------------------------------
// Loot File Management
// ------------------------------
func (m *FunctionsModule) initializeLootFiles() {
	m.LootMap["functions-commands"] = &internal.LootFile{
		Name:     "functions-commands",
		Contents: "# GCP Cloud Functions Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
	m.LootMap["functions-env-vars"] = &internal.LootFile{
		Name:     "functions-env-vars",
		Contents: "# Cloud Functions Environment Variables\n# Generated by CloudFox\n# Variable names that may hint at secrets\n\n",
	}
	m.LootMap["functions-secrets"] = &internal.LootFile{
		Name:     "functions-secrets",
		Contents: "# Cloud Functions Secret References\n# Generated by CloudFox\n# Secrets used by functions (names only)\n\n",
	}
}

func (m *FunctionsModule) addFunctionToLoot(fn FunctionsService.FunctionInfo) {
	// All commands for this function
	m.LootMap["functions-commands"].Contents += fmt.Sprintf(
		"## Function: %s (Project: %s, Region: %s)\n"+
			"# Runtime: %s, Trigger: %s\n"+
			"# Service Account: %s\n"+
			"# Public: %v, Ingress: %s\n",
		fn.Name, fn.ProjectID, fn.Region,
		fn.Runtime, fn.TriggerType,
		fn.ServiceAccount,
		fn.IsPublic, fn.IngressSettings,
	)

	if fn.TriggerURL != "" {
		m.LootMap["functions-commands"].Contents += fmt.Sprintf("# URL: %s\n", fn.TriggerURL)
	}

	if fn.SourceLocation != "" {
		m.LootMap["functions-commands"].Contents += fmt.Sprintf("# Source: %s (%s)\n", fn.SourceLocation, fn.SourceType)
	}

	m.LootMap["functions-commands"].Contents += fmt.Sprintf(
		"\n# Describe function:\n"+
			"gcloud functions describe %s --region=%s --project=%s --gen2\n"+
			"# Get IAM policy:\n"+
			"gcloud functions get-iam-policy %s --region=%s --project=%s --gen2\n"+
			"# Read logs:\n"+
			"gcloud functions logs read %s --region=%s --project=%s --gen2 --limit=50\n",
		fn.Name, fn.Region, fn.ProjectID,
		fn.Name, fn.Region, fn.ProjectID,
		fn.Name, fn.Region, fn.ProjectID,
	)

	// HTTP invocation commands
	if fn.TriggerType == "HTTP" && fn.TriggerURL != "" {
		m.LootMap["functions-commands"].Contents += fmt.Sprintf(
			"# Invoke (GET):\n"+
				"curl -s '%s'\n"+
				"# Invoke (POST with auth):\n"+
				"curl -s -X POST '%s' \\\n"+
				"  -H 'Authorization: Bearer $(gcloud auth print-identity-token)' \\\n"+
				"  -H 'Content-Type: application/json' \\\n"+
				"  -d '{\"test\": \"data\"}'\n",
			fn.TriggerURL,
			fn.TriggerURL,
		)
	}

	// Source download command
	if fn.SourceType == "GCS" && fn.SourceLocation != "" {
		m.LootMap["functions-commands"].Contents += fmt.Sprintf(
			"# Download source:\n"+
				"gsutil cp %s ./function-source-%s.zip\n",
			fn.SourceLocation, fn.Name,
		)
	}

	m.LootMap["functions-commands"].Contents += "\n"

	// Environment variable names (keep separate - useful for secret hunting)
	if len(fn.EnvVarNames) > 0 {
		m.LootMap["functions-env-vars"].Contents += fmt.Sprintf(
			"## Function: %s (Project: %s)\n",
			fn.Name, fn.ProjectID,
		)
		for _, varName := range fn.EnvVarNames {
			m.LootMap["functions-env-vars"].Contents += fmt.Sprintf("##   - %s\n", varName)
		}
		m.LootMap["functions-env-vars"].Contents += "\n"
	}

	// Secret references (keep separate - useful for secret hunting)
	if len(fn.SecretEnvVarNames) > 0 || len(fn.SecretVolumeNames) > 0 {
		m.LootMap["functions-secrets"].Contents += fmt.Sprintf(
			"## Function: %s (Project: %s)\n",
			fn.Name, fn.ProjectID,
		)
		if len(fn.SecretEnvVarNames) > 0 {
			m.LootMap["functions-secrets"].Contents += "## Secret Environment Variables:\n"
			for _, secretName := range fn.SecretEnvVarNames {
				m.LootMap["functions-secrets"].Contents += fmt.Sprintf("##   - %s\n", secretName)
			}
		}
		if len(fn.SecretVolumeNames) > 0 {
			m.LootMap["functions-secrets"].Contents += "## Secret Volumes:\n"
			for _, volName := range fn.SecretVolumeNames {
				m.LootMap["functions-secrets"].Contents += fmt.Sprintf("##   - %s\n", volName)
			}
		}
		m.LootMap["functions-secrets"].Contents += "\n"
	}
}

// ------------------------------
// Output Generation
// ------------------------------
func (m *FunctionsModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Functions table with one row per IAM binding
	header := []string{
		"Project Name",
		"Project ID",
		"Name",
		"Region",
		"State",
		"Runtime",
		"Trigger",
		"URL",
		"Ingress",
		"Public",
		"Service Account",
		"VPC Connector",
		"Secrets",
		"IAM Role",
		"IAM Member",
	}

	var body [][]string
	for _, fn := range m.Functions {
		// Format trigger info
		triggerInfo := fn.TriggerType
		if fn.TriggerEventType != "" {
			triggerInfo = fn.TriggerType
		}

		// Format URL - no truncation
		url := "-"
		if fn.TriggerURL != "" {
			url = fn.TriggerURL
		}

		// Format VPC connector
		vpcConnector := "-"
		if fn.VPCConnector != "" {
			vpcConnector = fn.VPCConnector
		}

		// Format secrets count
		secretsInfo := "-"
		totalSecrets := fn.SecretEnvVarCount + fn.SecretVolumeCount
		if totalSecrets > 0 {
			secretsInfo = fmt.Sprintf("%d", totalSecrets)
		}

		// Format service account - no truncation
		serviceAccount := fn.ServiceAccount
		if serviceAccount == "" {
			serviceAccount = "-"
		}

		// If function has IAM bindings, create one row per binding
		if len(fn.IAMBindings) > 0 {
			for _, binding := range fn.IAMBindings {
				body = append(body, []string{
					m.GetProjectName(fn.ProjectID),
					fn.ProjectID,
					fn.Name,
					fn.Region,
					fn.State,
					fn.Runtime,
					triggerInfo,
					url,
					fn.IngressSettings,
					boolToYesNo(fn.IsPublic),
					serviceAccount,
					vpcConnector,
					secretsInfo,
					binding.Role,
					binding.Member,
				})
			}
		} else {
			// Function has no IAM bindings - single row
			body = append(body, []string{
				m.GetProjectName(fn.ProjectID),
				fn.ProjectID,
				fn.Name,
				fn.Region,
				fn.State,
				fn.Runtime,
				triggerInfo,
				url,
				fn.IngressSettings,
				boolToYesNo(fn.IsPublic),
				serviceAccount,
				vpcConnector,
				secretsInfo,
				"-",
				"-",
			})
		}
	}

	// Collect loot files
	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	// Build table files
	tableFiles := []internal.TableFile{}
	if len(body) > 0 {
		tableFiles = append(tableFiles, internal.TableFile{
			Name:   globals.GCP_FUNCTIONS_MODULE_NAME,
			Header: header,
			Body:   body,
		})
	}

	output := FunctionsOutput{
		Table: tableFiles,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart(
		"gcp",
		m.Format,
		m.OutputDirectory,
		m.Verbosity,
		m.WrapTable,
		"project",
		m.ProjectIDs,
		scopeNames,
		m.Account,
		output,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_FUNCTIONS_MODULE_NAME)
		m.CommandCounter.Error++
	}
}
