package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	iapservice "github.com/BishopFox/cloudfox/gcp/services/iapService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPIAPCommand = &cobra.Command{
	Use:     globals.GCP_IAP_MODULE_NAME,
	Aliases: []string{"identity-aware-proxy"},
	Short:   "Enumerate Identity-Aware Proxy configurations",
	Long: `Enumerate Identity-Aware Proxy (IAP) configurations.

Features:
- Lists IAP tunnel destination groups
- Analyzes IAP settings and bindings
- Identifies overly permissive tunnel configurations
- Checks for public access to IAP resources`,
	Run: runGCPIAPCommand,
}

type IAPModule struct {
	gcpinternal.BaseGCPModule
	TunnelDestGroups []iapservice.TunnelDestGroup
	LootMap          map[string]*internal.LootFile
	mu               sync.Mutex
}

type IAPOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o IAPOutput) TableFiles() []internal.TableFile { return o.Table }
func (o IAPOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPIAPCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_IAP_MODULE_NAME)
	if err != nil {
		return
	}

	module := &IAPModule{
		BaseGCPModule:    gcpinternal.NewBaseGCPModule(cmdCtx),
		TunnelDestGroups: []iapservice.TunnelDestGroup{},
		LootMap:          make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *IAPModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_IAP_MODULE_NAME, m.processProject)

	if len(m.TunnelDestGroups) == 0 {
		logger.InfoM("No IAP tunnel destination groups found", globals.GCP_IAP_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d IAP tunnel destination group(s)",
		len(m.TunnelDestGroups)), globals.GCP_IAP_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *IAPModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating IAP in project: %s", projectID), globals.GCP_IAP_MODULE_NAME)
	}

	svc := iapservice.New()

	// Get tunnel destination groups
	groups, err := svc.ListTunnelDestGroups(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_IAP_MODULE_NAME,
			fmt.Sprintf("Could not enumerate IAP tunnel groups in project %s", projectID))
	} else {
		m.mu.Lock()
		m.TunnelDestGroups = append(m.TunnelDestGroups, groups...)
		for _, group := range groups {
			m.addToLoot(group)
		}
		m.mu.Unlock()
	}
}

func (m *IAPModule) initializeLootFiles() {
	m.LootMap["iap-commands"] = &internal.LootFile{
		Name:     "iap-commands",
		Contents: "# IAP Commands\n# Generated by CloudFox\n\n",
	}
}

func (m *IAPModule) addToLoot(group iapservice.TunnelDestGroup) {
	m.LootMap["iap-commands"].Contents += fmt.Sprintf(
		"## Tunnel Destination Group: %s (Project: %s, Region: %s)\n"+
			"# CIDRs: %s\n"+
			"# FQDNs: %s\n\n"+
			"# Describe tunnel destination group:\n"+
			"gcloud iap tcp dest-groups describe %s --region=%s --project=%s\n\n"+
			"# List IAM policy for tunnel destination group:\n"+
			"gcloud iap tcp dest-groups get-iam-policy %s --region=%s --project=%s\n\n",
		group.Name, group.ProjectID, group.Region,
		strings.Join(group.CIDRs, ", "),
		strings.Join(group.FQDNs, ", "),
		group.Name, group.Region, group.ProjectID,
		group.Name, group.Region, group.ProjectID,
	)
}

func (m *IAPModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Tunnel Destination Groups table with one row per IAM binding
	header := []string{
		"Project Name",
		"Project ID",
		"Name",
		"Region",
		"CIDRs",
		"FQDNs",
		"IAM Role",
		"IAM Member",
	}

	var body [][]string
	for _, group := range m.TunnelDestGroups {
		// No truncation - show full content
		cidrs := strings.Join(group.CIDRs, ", ")
		if cidrs == "" {
			cidrs = "-"
		}
		fqdns := strings.Join(group.FQDNs, ", ")
		if fqdns == "" {
			fqdns = "-"
		}

		// If group has IAM bindings, create one row per binding
		if len(group.IAMBindings) > 0 {
			for _, binding := range group.IAMBindings {
				body = append(body, []string{
					m.GetProjectName(group.ProjectID),
					group.ProjectID,
					group.Name,
					group.Region,
					cidrs,
					fqdns,
					binding.Role,
					binding.Member,
				})
			}
		} else {
			// No IAM bindings - single row
			body = append(body, []string{
				m.GetProjectName(group.ProjectID),
				group.ProjectID,
				group.Name,
				group.Region,
				cidrs,
				fqdns,
				"-",
				"-",
			})
		}
	}

	if len(body) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "iap-tunnel-groups",
			Header: header,
			Body:   body,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := IAPOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_IAP_MODULE_NAME)
	}
}
