package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	loadbalancerservice "github.com/BishopFox/cloudfox/gcp/services/loadbalancerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPLoadBalancersCommand = &cobra.Command{
	Use:     globals.GCP_LOADBALANCERS_MODULE_NAME,
	Aliases: []string{"lb", "lbs"},
	Short:   "Enumerate Load Balancers",
	Long: `Enumerate Load Balancers and related configurations.

Features:
- Lists all forwarding rules (global and regional)
- Shows backend services and health checks
- Analyzes SSL policies for weak configurations
- Identifies external vs internal load balancers
- Checks for Cloud Armor security policies`,
	Run: runGCPLoadBalancersCommand,
}

type LoadBalancersModule struct {
	gcpinternal.BaseGCPModule
	LoadBalancers   []loadbalancerservice.LoadBalancerInfo
	SSLPolicies     []loadbalancerservice.SSLPolicyInfo
	BackendServices []loadbalancerservice.BackendServiceInfo
	LootMap         map[string]*internal.LootFile
	mu              sync.Mutex
}

type LoadBalancersOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o LoadBalancersOutput) TableFiles() []internal.TableFile { return o.Table }
func (o LoadBalancersOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPLoadBalancersCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_LOADBALANCERS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &LoadBalancersModule{
		BaseGCPModule:   gcpinternal.NewBaseGCPModule(cmdCtx),
		LoadBalancers:   []loadbalancerservice.LoadBalancerInfo{},
		SSLPolicies:     []loadbalancerservice.SSLPolicyInfo{},
		BackendServices: []loadbalancerservice.BackendServiceInfo{},
		LootMap:         make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *LoadBalancersModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_LOADBALANCERS_MODULE_NAME, m.processProject)

	if len(m.LoadBalancers) == 0 {
		logger.InfoM("No load balancers found", globals.GCP_LOADBALANCERS_MODULE_NAME)
		return
	}

	externalCount := 0
	for _, lb := range m.LoadBalancers {
		if lb.Scheme == "EXTERNAL" {
			externalCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d load balancer(s) (%d external), %d SSL policies, %d backend services",
		len(m.LoadBalancers), externalCount, len(m.SSLPolicies), len(m.BackendServices)), globals.GCP_LOADBALANCERS_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *LoadBalancersModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating load balancers in project: %s", projectID), globals.GCP_LOADBALANCERS_MODULE_NAME)
	}

	svc := loadbalancerservice.New()

	// Get load balancers
	lbs, err := svc.ListLoadBalancers(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_LOADBALANCERS_MODULE_NAME,
			fmt.Sprintf("Could not list load balancers in project %s", projectID))
	} else {
		m.mu.Lock()
		m.LoadBalancers = append(m.LoadBalancers, lbs...)
		m.mu.Unlock()
	}

	// Get SSL policies
	sslPolicies, err := svc.ListSSLPolicies(projectID)
	if err == nil {
		m.mu.Lock()
		m.SSLPolicies = append(m.SSLPolicies, sslPolicies...)
		m.mu.Unlock()
	}

	// Get backend services
	backends, err := svc.ListBackendServices(projectID)
	if err == nil {
		m.mu.Lock()
		m.BackendServices = append(m.BackendServices, backends...)
		m.mu.Unlock()
	}

	m.mu.Lock()
	for _, lb := range lbs {
		m.addToLoot(lb)
	}
	m.mu.Unlock()
}

func (m *LoadBalancersModule) initializeLootFiles() {
	m.LootMap["loadbalancers-commands"] = &internal.LootFile{
		Name:     "loadbalancers-commands",
		Contents: "# Load Balancer Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
}

func (m *LoadBalancersModule) addToLoot(lb loadbalancerservice.LoadBalancerInfo) {
	m.LootMap["loadbalancers-commands"].Contents += fmt.Sprintf(
		"## Load Balancer: %s (Project: %s)\n"+
			"# Type: %s, Scheme: %s, IP: %s, Port: %s\n\n",
		lb.Name, lb.ProjectID, lb.Type, lb.Scheme, lb.IPAddress, lb.Port)

	// Describe forwarding rule
	if lb.Region == "global" {
		m.LootMap["loadbalancers-commands"].Contents += fmt.Sprintf(
			"# Describe global forwarding rule:\n"+
				"gcloud compute forwarding-rules describe %s --global --project=%s\n\n",
			lb.Name, lb.ProjectID)
	} else {
		m.LootMap["loadbalancers-commands"].Contents += fmt.Sprintf(
			"# Describe regional forwarding rule:\n"+
				"gcloud compute forwarding-rules describe %s --region=%s --project=%s\n\n",
			lb.Name, lb.Region, lb.ProjectID)
	}

	// Backend service commands
	for _, backend := range lb.BackendServices {
		m.LootMap["loadbalancers-commands"].Contents += fmt.Sprintf(
			"# Describe backend service:\n"+
				"gcloud compute backend-services describe %s --global --project=%s\n\n",
			backend, lb.ProjectID)
	}
}

func (m *LoadBalancersModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Load Balancers table
	lbHeader := []string{"Project Name", "Project ID", "Name", "Type", "Scheme", "Region", "IP Address", "Port", "Backend Services", "Security Policy"}
	var lbBody [][]string
	for _, lb := range m.LoadBalancers {
		backends := "-"
		if len(lb.BackendServices) > 0 {
			backends = strings.Join(lb.BackendServices, ", ")
		}
		secPolicy := "-"
		if lb.SecurityPolicy != "" {
			secPolicy = lb.SecurityPolicy
		}
		lbBody = append(lbBody, []string{
			m.GetProjectName(lb.ProjectID),
			lb.ProjectID,
			lb.Name,
			lb.Type,
			lb.Scheme,
			lb.Region,
			lb.IPAddress,
			lb.Port,
			backends,
			secPolicy,
		})
	}
	tables = append(tables, internal.TableFile{
		Name:   "load-balancers",
		Header: lbHeader,
		Body:   lbBody,
	})

	// SSL Policies table
	if len(m.SSLPolicies) > 0 {
		sslHeader := []string{"Project Name", "Project ID", "Name", "Min TLS Version", "Profile", "Custom Features"}
		var sslBody [][]string
		for _, policy := range m.SSLPolicies {
			customFeatures := "-"
			if len(policy.CustomFeatures) > 0 {
				customFeatures = strings.Join(policy.CustomFeatures, ", ")
			}
			sslBody = append(sslBody, []string{
				m.GetProjectName(policy.ProjectID),
				policy.ProjectID,
				policy.Name,
				policy.MinTLSVersion,
				policy.Profile,
				customFeatures,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "ssl-policies",
			Header: sslHeader,
			Body:   sslBody,
		})
	}

	// Backend Services table
	if len(m.BackendServices) > 0 {
		beHeader := []string{"Project Name", "Project ID", "Name", "Protocol", "Port", "Security Policy", "CDN Enabled", "Health Check", "Session Affinity", "Backends"}
		var beBody [][]string
		for _, be := range m.BackendServices {
			secPolicy := "-"
			if be.SecurityPolicy != "" {
				secPolicy = be.SecurityPolicy
			}
			healthCheck := "-"
			if be.HealthCheck != "" {
				healthCheck = be.HealthCheck
			}
			sessionAffinity := "-"
			if be.SessionAffinity != "" {
				sessionAffinity = be.SessionAffinity
			}
			backends := "-"
			if len(be.Backends) > 0 {
				backends = strings.Join(be.Backends, ", ")
			}
			beBody = append(beBody, []string{
				m.GetProjectName(be.ProjectID),
				be.ProjectID,
				be.Name,
				be.Protocol,
				fmt.Sprintf("%d", be.Port),
				secPolicy,
				boolToYesNo(be.EnableCDN),
				healthCheck,
				sessionAffinity,
				backends,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "backend-services",
			Header: beHeader,
			Body:   beBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := LoadBalancersOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_LOADBALANCERS_MODULE_NAME)
	}
}
