package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	memorystoreservice "github.com/BishopFox/cloudfox/gcp/services/memorystoreService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPMemorystoreCommand = &cobra.Command{
	Use:     globals.GCP_MEMORYSTORE_MODULE_NAME,
	Aliases: []string{"redis", "cache"},
	Short:   "Enumerate Memorystore (Redis) instances",
	Long: `Enumerate Memorystore for Redis instances with security analysis.

Features:
- Lists all Redis instances
- Shows authentication and encryption status
- Identifies network configuration
- Detects security misconfigurations`,
	Run: runGCPMemorystoreCommand,
}

type MemorystoreModule struct {
	gcpinternal.BaseGCPModule
	RedisInstances []memorystoreservice.RedisInstanceInfo
	LootMap        map[string]*internal.LootFile
	mu             sync.Mutex
}

type MemorystoreOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o MemorystoreOutput) TableFiles() []internal.TableFile { return o.Table }
func (o MemorystoreOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPMemorystoreCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_MEMORYSTORE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &MemorystoreModule{
		BaseGCPModule:  gcpinternal.NewBaseGCPModule(cmdCtx),
		RedisInstances: []memorystoreservice.RedisInstanceInfo{},
		LootMap:        make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *MemorystoreModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_MEMORYSTORE_MODULE_NAME, m.processProject)

	if len(m.RedisInstances) == 0 {
		logger.InfoM("No Memorystore instances found", globals.GCP_MEMORYSTORE_MODULE_NAME)
		return
	}

	noAuth := 0
	for _, instance := range m.RedisInstances {
		if !instance.AuthEnabled {
			noAuth++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d Redis instance(s) (%d without auth)",
		len(m.RedisInstances), noAuth), globals.GCP_MEMORYSTORE_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

func (m *MemorystoreModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Memorystore in project: %s", projectID), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}

	svc := memorystoreservice.New()
	instances, err := svc.ListRedisInstances(projectID)
	if err != nil {
		if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
			logger.InfoM(fmt.Sprintf("Could not list Redis instances: %v", err), globals.GCP_MEMORYSTORE_MODULE_NAME)
		}
		return
	}

	m.mu.Lock()
	m.RedisInstances = append(m.RedisInstances, instances...)
	for _, instance := range instances {
		m.addInstanceToLoot(instance)
	}
	m.mu.Unlock()
}

func (m *MemorystoreModule) initializeLootFiles() {
	m.LootMap["memorystore-instances"] = &internal.LootFile{
		Name:     "memorystore-instances",
		Contents: "# Memorystore Redis Instances\n# Generated by CloudFox\n\n",
	}
	m.LootMap["memorystore-endpoints"] = &internal.LootFile{
		Name:     "memorystore-endpoints",
		Contents: "",
	}
}

func (m *MemorystoreModule) addInstanceToLoot(instance memorystoreservice.RedisInstanceInfo) {
	m.LootMap["memorystore-instances"].Contents += fmt.Sprintf(
		"# Instance: %s\n# Host: %s:%d\n# Auth: %v\n# Encryption: %s\n\n",
		instance.Name,
		instance.Host,
		instance.Port,
		instance.AuthEnabled,
		instance.TransitEncryption,
	)
	m.LootMap["memorystore-endpoints"].Contents += fmt.Sprintf("%s:%d\n", instance.Host, instance.Port)
}

func (m *MemorystoreModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Name",
		"Location",
		"Tier",
		"Memory (GB)",
		"Version",
		"Host:Port",
		"Auth",
		"Encryption",
		"State",
		"Risk",
		"Project",
	}

	var body [][]string
	for _, instance := range m.RedisInstances {
		auth := "No"
		if instance.AuthEnabled {
			auth = "Yes"
		}
		body = append(body, []string{
			instance.Name,
			instance.Location,
			instance.Tier,
			fmt.Sprintf("%d", instance.MemorySizeGB),
			instance.RedisVersion,
			fmt.Sprintf("%s:%d", instance.Host, instance.Port),
			auth,
			instance.TransitEncryption,
			instance.State,
			instance.RiskLevel,
			instance.ProjectID,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# Generated by CloudFox\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	tables := []internal.TableFile{{Name: "memorystore", Header: header, Body: body}}

	output := MemorystoreOutput{Table: tables, Loot: lootFiles}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, m.ProjectIDs, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}
}
