package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	memorystoreservice "github.com/BishopFox/cloudfox/gcp/services/memorystoreService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPMemorystoreCommand = &cobra.Command{
	Use:     globals.GCP_MEMORYSTORE_MODULE_NAME,
	Aliases: []string{"redis", "cache"},
	Short:   "Enumerate Memorystore (Redis) instances",
	Long: `Enumerate Memorystore for Redis instances with security analysis.

Features:
- Lists all Redis instances
- Shows authentication and encryption status
- Identifies network configuration
- Detects security misconfigurations`,
	Run: runGCPMemorystoreCommand,
}

type MemorystoreModule struct {
	gcpinternal.BaseGCPModule
	RedisInstances []memorystoreservice.RedisInstanceInfo
	LootMap        map[string]*internal.LootFile
	mu             sync.Mutex
}

type MemorystoreOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o MemorystoreOutput) TableFiles() []internal.TableFile { return o.Table }
func (o MemorystoreOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPMemorystoreCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_MEMORYSTORE_MODULE_NAME)
	if err != nil {
		return
	}

	module := &MemorystoreModule{
		BaseGCPModule:  gcpinternal.NewBaseGCPModule(cmdCtx),
		RedisInstances: []memorystoreservice.RedisInstanceInfo{},
		LootMap:        make(map[string]*internal.LootFile),
	}

	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *MemorystoreModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_MEMORYSTORE_MODULE_NAME, m.processProject)

	if len(m.RedisInstances) == 0 {
		logger.InfoM("No Memorystore instances found", globals.GCP_MEMORYSTORE_MODULE_NAME)
		return
	}

	noAuth := 0
	for _, instance := range m.RedisInstances {
		if !instance.AuthEnabled {
			noAuth++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d Redis instance(s) (%d without auth)",
		len(m.RedisInstances), noAuth), globals.GCP_MEMORYSTORE_MODULE_NAME)

	m.writeOutput(ctx, logger)
}

func (m *MemorystoreModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Memorystore in project: %s", projectID), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}

	svc := memorystoreservice.New()
	instances, err := svc.ListRedisInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_MEMORYSTORE_MODULE_NAME,
			fmt.Sprintf("Could not list Redis instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.RedisInstances = append(m.RedisInstances, instances...)
	for _, instance := range instances {
		m.addInstanceToLoot(instance)
	}
	m.mu.Unlock()
}

func (m *MemorystoreModule) initializeLootFiles() {
	m.LootMap["memorystore-commands"] = &internal.LootFile{
		Name:     "memorystore-commands",
		Contents: "# Memorystore Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
}

func (m *MemorystoreModule) addInstanceToLoot(instance memorystoreservice.RedisInstanceInfo) {
	m.LootMap["memorystore-commands"].Contents += fmt.Sprintf(
		"## Instance: %s (Project: %s, Location: %s)\n"+
			"# Host: %s:%d\n"+
			"# Auth: %v, Encryption: %s\n\n",
		instance.Name, instance.ProjectID, instance.Location,
		instance.Host, instance.Port,
		instance.AuthEnabled, instance.TransitEncryption,
	)

	// gcloud commands
	m.LootMap["memorystore-commands"].Contents += fmt.Sprintf(
		"# Describe instance:\n"+
			"gcloud redis instances describe %s --region=%s --project=%s\n\n",
		instance.Name, instance.Location, instance.ProjectID,
	)

	// Auth string command (if auth enabled)
	if instance.AuthEnabled {
		m.LootMap["memorystore-commands"].Contents += fmt.Sprintf(
			"# Get auth string:\n"+
				"gcloud redis instances get-auth-string %s --region=%s --project=%s\n\n",
			instance.Name, instance.Location, instance.ProjectID,
		)
	}

	// Redis CLI connection command
	authStr := ""
	if instance.AuthEnabled {
		authStr = " -a $(gcloud redis instances get-auth-string " + instance.Name +
			" --region=" + instance.Location + " --project=" + instance.ProjectID +
			" --format='value(authString)')"
	}
	m.LootMap["memorystore-commands"].Contents += fmt.Sprintf(
		"# Connect to Redis (from a VM in the same VPC):\n"+
			"redis-cli -h %s -p %d%s\n\n",
		instance.Host, instance.Port, authStr,
	)
}

// extractNetworkName extracts the network name from the full resource path
func extractNetworkName(network string) string {
	if network == "" {
		return "-"
	}
	parts := strings.Split(network, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return network
}

func (m *MemorystoreModule) writeOutput(ctx context.Context, logger internal.Logger) {
	header := []string{
		"Project Name",
		"Project ID",
		"Name",
		"Location",
		"Tier",
		"Memory (GB)",
		"Version",
		"Host:Port",
		"Auth Enabled",
		"Transit Encryption",
		"State",
		"Network",
		"Connect Mode",
	}

	var body [][]string
	for _, instance := range m.RedisInstances {
		transitEncryption := instance.TransitEncryption
		if transitEncryption == "" {
			transitEncryption = "DISABLED"
		}
		body = append(body, []string{
			m.GetProjectName(instance.ProjectID),
			instance.ProjectID,
			instance.Name,
			instance.Location,
			instance.Tier,
			fmt.Sprintf("%d", instance.MemorySizeGB),
			instance.RedisVersion,
			fmt.Sprintf("%s:%d", instance.Host, instance.Port),
			boolToYesNo(instance.AuthEnabled),
			transitEncryption,
			instance.State,
			extractNetworkName(instance.AuthorizedNetwork),
			instance.ConnectMode,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	tables := []internal.TableFile{{Name: "memorystore", Header: header, Body: body}}

	output := MemorystoreOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_MEMORYSTORE_MODULE_NAME)
	}
}
