package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	notebooksservice "github.com/BishopFox/cloudfox/gcp/services/notebooksService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPNotebooksCommand = &cobra.Command{
	Use:     globals.GCP_NOTEBOOKS_MODULE_NAME,
	Aliases: []string{"nb", "jupyter", "workbench"},
	Short:   "Enumerate Vertex AI Workbench notebooks",
	Long: `Enumerate Vertex AI Workbench and legacy notebook instances.

Features:
- Lists all notebook instances across locations
- Shows service account configuration
- Identifies public IP exposure
- Checks for GPU attachments
- Analyzes proxy access settings`,
	Run: runGCPNotebooksCommand,
}

type NotebooksModule struct {
	gcpinternal.BaseGCPModule
	Instances []notebooksservice.NotebookInstanceInfo
	Runtimes  []notebooksservice.RuntimeInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

type NotebooksOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o NotebooksOutput) TableFiles() []internal.TableFile { return o.Table }
func (o NotebooksOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPNotebooksCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_NOTEBOOKS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &NotebooksModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Instances:     []notebooksservice.NotebookInstanceInfo{},
		Runtimes:      []notebooksservice.RuntimeInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *NotebooksModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_NOTEBOOKS_MODULE_NAME, m.processProject)

	if len(m.Instances) == 0 && len(m.Runtimes) == 0 {
		logger.InfoM("No notebook instances found", globals.GCP_NOTEBOOKS_MODULE_NAME)
		return
	}

	publicCount := 0
	for _, instance := range m.Instances {
		if !instance.NoPublicIP {
			publicCount++
		}
	}

	logger.SuccessM(fmt.Sprintf("Found %d notebook instance(s) (%d with public IP), %d runtime(s)",
		len(m.Instances), publicCount, len(m.Runtimes)), globals.GCP_NOTEBOOKS_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *NotebooksModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating notebooks in project: %s", projectID), globals.GCP_NOTEBOOKS_MODULE_NAME)
	}

	svc := notebooksservice.New()

	// Get instances
	instances, err := svc.ListInstances(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_NOTEBOOKS_MODULE_NAME,
			fmt.Sprintf("Could not list notebook instances in project %s", projectID))
	} else {
		m.mu.Lock()
		m.Instances = append(m.Instances, instances...)
		for _, instance := range instances {
			m.addToLoot(instance)
		}
		m.mu.Unlock()
	}

	// Get runtimes
	runtimes, err := svc.ListRuntimes(projectID)
	if err == nil {
		m.mu.Lock()
		m.Runtimes = append(m.Runtimes, runtimes...)
		m.mu.Unlock()
	}
}

func (m *NotebooksModule) initializeLootFiles() {
	m.LootMap["notebooks-commands"] = &internal.LootFile{
		Name:     "notebooks-commands",
		Contents: "# Notebook Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
}

func (m *NotebooksModule) addToLoot(instance notebooksservice.NotebookInstanceInfo) {
	m.LootMap["notebooks-commands"].Contents += fmt.Sprintf(
		"## Instance: %s (Project: %s, Location: %s)\n"+
			"# State: %s, Service Account: %s\n"+
			"# Public IP: %s, Proxy Access: %s\n",
		instance.Name, instance.ProjectID, instance.Location,
		instance.State, instance.ServiceAccount,
		boolToYesNo(!instance.NoPublicIP), boolToYesNo(!instance.NoProxyAccess),
	)

	if instance.ProxyUri != "" {
		m.LootMap["notebooks-commands"].Contents += fmt.Sprintf(
			"# Proxy URI: %s\n", instance.ProxyUri)
	}

	m.LootMap["notebooks-commands"].Contents += fmt.Sprintf(
		"\n# Describe instance:\n"+
			"gcloud notebooks instances describe %s --location=%s --project=%s\n\n"+
			"# Get JupyterLab proxy URL:\n"+
			"gcloud notebooks instances describe %s --location=%s --project=%s --format='value(proxyUri)'\n\n"+
			"# Start instance (if stopped):\n"+
			"gcloud notebooks instances start %s --location=%s --project=%s\n\n"+
			"# Stop instance:\n"+
			"gcloud notebooks instances stop %s --location=%s --project=%s\n\n",
		instance.Name, instance.Location, instance.ProjectID,
		instance.Name, instance.Location, instance.ProjectID,
		instance.Name, instance.Location, instance.ProjectID,
		instance.Name, instance.Location, instance.ProjectID,
	)
}

func (m *NotebooksModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Instances table
	if len(m.Instances) > 0 {
		header := []string{
			"Project Name",
			"Project ID",
			"Name",
			"Location",
			"State",
			"Machine Type",
			"Service Account",
			"Network",
			"Subnet",
			"Public IP",
			"Proxy Access",
			"Proxy URI",
			"GPU",
			"Creator",
		}
		var body [][]string
		for _, instance := range m.Instances {
			gpu := "-"
			if instance.AcceleratorCount > 0 {
				gpu = fmt.Sprintf("%s x%d", instance.AcceleratorType, instance.AcceleratorCount)
			}
			sa := instance.ServiceAccount
			if sa == "" {
				sa = "(default)"
			}
			network := instance.Network
			if network == "" {
				network = "-"
			}
			subnet := instance.Subnet
			if subnet == "" {
				subnet = "-"
			}
			proxyUri := instance.ProxyUri
			if proxyUri == "" {
				proxyUri = "-"
			}
			creator := instance.Creator
			if creator == "" {
				creator = "-"
			}
			body = append(body, []string{
				m.GetProjectName(instance.ProjectID),
				instance.ProjectID,
				instance.Name,
				instance.Location,
				instance.State,
				instance.MachineType,
				sa,
				network,
				subnet,
				boolToYesNo(!instance.NoPublicIP),
				boolToYesNo(!instance.NoProxyAccess),
				proxyUri,
				gpu,
				creator,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "notebook-instances",
			Header: header,
			Body:   body,
		})
	}

	// Runtimes table
	if len(m.Runtimes) > 0 {
		header := []string{
			"Project Name",
			"Project ID",
			"Name",
			"Location",
			"State",
			"Type",
			"Machine Type",
			"Service Account",
			"Network",
			"Subnet",
		}
		var body [][]string
		for _, runtime := range m.Runtimes {
			sa := runtime.ServiceAccount
			if sa == "" {
				sa = "-"
			}
			network := runtime.Network
			if network == "" {
				network = "-"
			}
			subnet := runtime.Subnet
			if subnet == "" {
				subnet = "-"
			}
			body = append(body, []string{
				m.GetProjectName(runtime.ProjectID),
				runtime.ProjectID,
				runtime.Name,
				runtime.Location,
				runtime.State,
				runtime.RuntimeType,
				runtime.MachineType,
				sa,
				network,
				subnet,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "notebook-runtimes",
			Header: header,
			Body:   body,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := NotebooksOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_NOTEBOOKS_MODULE_NAME)
	}
}
