package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	secretmanager "cloud.google.com/go/secretmanager/apiv1"
	SecretsService "github.com/BishopFox/cloudfox/gcp/services/secretsService"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	"github.com/spf13/cobra"
)

var GCPSecretsCommand = &cobra.Command{
	Use:     globals.GCP_SECRETS_MODULE_NAME,
	Aliases: []string{"secretmanager", "sm"},
	Short:   "Enumerate GCP Secret Manager secrets with security configuration",
	Long: `Enumerate GCP Secret Manager secrets across projects with security-relevant details.

Features:
- Lists all secrets with metadata and security configuration
- Shows encryption type (Google-managed vs CMEK)
- Shows replication configuration (automatic vs user-managed)
- Shows expiration and rotation settings
- Enumerates IAM policies per secret
- Generates gcloud commands for secret access
- Generates exploitation commands for secret extraction

Security Columns:
- Encryption: "Google-managed" or "CMEK" (customer-managed keys)
- Replication: "automatic" or "user-managed" with locations
- Rotation: Whether automatic rotation is enabled
- Expiration: Whether the secret has an expiration time/TTL
- VersionDestroyTTL: Delayed destruction period for old versions`,
	Run: runGCPSecretsCommand,
}

// ------------------------------
// Module Struct with embedded BaseGCPModule
// ------------------------------
type SecretsModule struct {
	gcpinternal.BaseGCPModule

	// Module-specific fields
	Secrets []SecretsService.SecretInfo
	LootMap map[string]*internal.LootFile
	client  *secretmanager.Client
	mu      sync.Mutex
}

// ------------------------------
// Output Struct implementing CloudfoxOutput interface
// ------------------------------
type SecretsOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o SecretsOutput) TableFiles() []internal.TableFile { return o.Table }
func (o SecretsOutput) LootFiles() []internal.LootFile   { return o.Loot }

// ------------------------------
// Command Entry Point
// ------------------------------
func runGCPSecretsCommand(cmd *cobra.Command, args []string) {
	// Initialize command context
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_SECRETS_MODULE_NAME)
	if err != nil {
		return // Error already logged
	}

	// Create Secret Manager client
	client, err := secretmanager.NewClient(cmdCtx.Ctx)
	if err != nil {
		cmdCtx.Logger.ErrorM(fmt.Sprintf("Failed to create Secret Manager client: %v", err), globals.GCP_SECRETS_MODULE_NAME)
		return
	}
	defer client.Close()

	// Create module instance
	module := &SecretsModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Secrets:       []SecretsService.SecretInfo{},
		LootMap:       make(map[string]*internal.LootFile),
		client:        client,
	}

	// Initialize loot files
	module.initializeLootFiles()

	// Execute enumeration
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

// ------------------------------
// Module Execution
// ------------------------------
func (m *SecretsModule) Execute(ctx context.Context, logger internal.Logger) {
	// Run enumeration with concurrency
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_SECRETS_MODULE_NAME, m.processProject)

	// Check results
	if len(m.Secrets) == 0 {
		logger.InfoM("No secrets found", globals.GCP_SECRETS_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d secret(s)", len(m.Secrets)), globals.GCP_SECRETS_MODULE_NAME)

	// Write output
	m.writeOutput(ctx, logger)
}

// ------------------------------
// Project Processor (called concurrently for each project)
// ------------------------------
func (m *SecretsModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating secrets in project: %s", projectID), globals.GCP_SECRETS_MODULE_NAME)
	}

	// Create service and fetch secrets
	ss := SecretsService.New(m.client)
	secrets, err := ss.Secrets(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_SECRETS_MODULE_NAME,
			fmt.Sprintf("Could not enumerate secrets in project %s", projectID))
		return
	}

	// Thread-safe append
	m.mu.Lock()
	m.Secrets = append(m.Secrets, secrets...)

	// Generate loot for each secret
	for _, secret := range secrets {
		m.addSecretToLoot(secret)
	}
	m.mu.Unlock()

	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Found %d secret(s) in project %s", len(secrets), projectID), globals.GCP_SECRETS_MODULE_NAME)
	}
}

// ------------------------------
// Loot File Management
// ------------------------------
func (m *SecretsModule) initializeLootFiles() {
	m.LootMap["secrets-commands"] = &internal.LootFile{
		Name:     "secrets-commands",
		Contents: "# GCP Secret Manager Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
}

func (m *SecretsModule) addSecretToLoot(secret SecretsService.SecretInfo) {
	// Extract secret name from full path
	secretName := getSecretShortName(secret.Name)

	m.LootMap["secrets-commands"].Contents += fmt.Sprintf(
		"# ==========================================\n"+
			"# SECRET: %s (Project: %s)\n"+
			"# ==========================================\n"+
			"# Encryption: %s, Replication: %s, Rotation: %s\n"+
			"# Created: %s\n",
		secretName, secret.ProjectID,
		secret.EncryptionType, secret.ReplicationType, secret.Rotation,
		secret.CreationTime,
	)

	// KMS key info
	if secret.KMSKeyName != "" {
		m.LootMap["secrets-commands"].Contents += fmt.Sprintf("# KMS Key: %s\n", secret.KMSKeyName)
	}

	// Rotation info
	if secret.Rotation == "enabled" {
		if secret.RotationPeriod != "" {
			m.LootMap["secrets-commands"].Contents += fmt.Sprintf("# Rotation Period: %s\n", secret.RotationPeriod)
		}
		if secret.NextRotationTime != "" {
			m.LootMap["secrets-commands"].Contents += fmt.Sprintf("# Next Rotation: %s\n", secret.NextRotationTime)
		}
	}

	// IAM bindings
	if len(secret.IAMBindings) > 0 {
		m.LootMap["secrets-commands"].Contents += "# IAM Bindings:\n"
		for _, binding := range secret.IAMBindings {
			m.LootMap["secrets-commands"].Contents += fmt.Sprintf(
				"#   %s: %s\n",
				binding.Role,
				strings.Join(binding.Members, ", "),
			)
		}
	}

	// Commands
	m.LootMap["secrets-commands"].Contents += fmt.Sprintf(
		"\n# Describe secret:\n"+
			"gcloud secrets describe %s --project=%s\n"+
			"# List versions:\n"+
			"gcloud secrets versions list %s --project=%s\n"+
			"# Get IAM policy:\n"+
			"gcloud secrets get-iam-policy %s --project=%s\n"+
			"# Access latest version:\n"+
			"gcloud secrets versions access latest --secret=%s --project=%s\n"+
			"# Download all versions:\n"+
			"for v in $(gcloud secrets versions list %s --project=%s --format='value(name)'); do\n"+
			"  echo \"=== Version $v ===\"\n"+
			"  gcloud secrets versions access $v --secret=%s --project=%s\n"+
			"done\n"+
			"# Add a new version:\n"+
			"echo -n 'new-secret-value' | gcloud secrets versions add %s --project=%s --data-file=-\n\n",
		secretName, secret.ProjectID,
		secretName, secret.ProjectID,
		secretName, secret.ProjectID,
		secretName, secret.ProjectID,
		secretName, secret.ProjectID,
		secretName, secret.ProjectID,
		secretName, secret.ProjectID,
	)
}


// ------------------------------
// Helper functions
// ------------------------------

// getSecretShortName extracts the short name from a full secret resource path
func getSecretShortName(fullName string) string {
	parts := strings.Split(fullName, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return fullName
}

// getSecretMemberType extracts the member type from a GCP IAM member string
func getSecretMemberType(member string) string {
	switch {
	case member == "allUsers":
		return "PUBLIC"
	case member == "allAuthenticatedUsers":
		return "ALL_AUTHENTICATED"
	case strings.HasPrefix(member, "user:"):
		return "User"
	case strings.HasPrefix(member, "serviceAccount:"):
		return "ServiceAccount"
	case strings.HasPrefix(member, "group:"):
		return "Group"
	case strings.HasPrefix(member, "domain:"):
		return "Domain"
	case strings.HasPrefix(member, "projectOwner:"):
		return "ProjectOwner"
	case strings.HasPrefix(member, "projectEditor:"):
		return "ProjectEditor"
	case strings.HasPrefix(member, "projectViewer:"):
		return "ProjectViewer"
	case strings.HasPrefix(member, "deleted:"):
		return "Deleted"
	default:
		return "Unknown"
	}
}

// ------------------------------
// Output Generation
// ------------------------------
func (m *SecretsModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Combined table with IAM columns (one row per IAM member)
	header := []string{
		"Project Name",
		"Project ID",
		"Name",
		"Encryption",
		"KMS Key",
		"Replication",
		"Rotation",
		"Rotation Period",
		"Next Rotation",
		"Expiration",
		"Destroy TTL",
		"Created",
		"IAM Role",
		"Member Type",
		"IAM Member",
	}

	var body [][]string
	for _, secret := range m.Secrets {
		secretName := getSecretShortName(secret.Name)

		// Format expiration
		expiration := "-"
		if secret.HasExpiration {
			if secret.ExpireTime != "" {
				expiration = secret.ExpireTime
			} else if secret.TTL != "" {
				expiration = "TTL: " + secret.TTL
			}
		}

		// Format version destroy TTL
		destroyTTL := "-"
		if secret.VersionDestroyTTL != "" {
			destroyTTL = secret.VersionDestroyTTL
		}

		// Format KMS key (no truncation)
		kmsKey := "-"
		if secret.KMSKeyName != "" {
			kmsKey = secret.KMSKeyName
		}

		// Format rotation period
		rotationPeriod := "-"
		if secret.RotationPeriod != "" {
			rotationPeriod = secret.RotationPeriod
		}

		// Format next rotation
		nextRotation := "-"
		if secret.NextRotationTime != "" {
			nextRotation = secret.NextRotationTime
		}

		// One row per IAM member
		if len(secret.IAMBindings) > 0 {
			for _, binding := range secret.IAMBindings {
				for _, member := range binding.Members {
					memberType := getSecretMemberType(member)
					body = append(body, []string{
						m.GetProjectName(secret.ProjectID),
						secret.ProjectID,
						secretName,
						secret.EncryptionType,
						kmsKey,
						secret.ReplicationType,
						secret.Rotation,
						rotationPeriod,
						nextRotation,
						expiration,
						destroyTTL,
						secret.CreationTime,
						binding.Role,
						memberType,
						member,
					})
				}
			}
		} else {
			// Secret with no IAM bindings
			body = append(body, []string{
				m.GetProjectName(secret.ProjectID),
				secret.ProjectID,
				secretName,
				secret.EncryptionType,
				kmsKey,
				secret.ReplicationType,
				secret.Rotation,
				rotationPeriod,
				nextRotation,
				expiration,
				destroyTTL,
				secret.CreationTime,
				"-",
				"-",
				"-",
			})
		}
	}

	// Collect loot files
	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	// Build table files
	tableFiles := []internal.TableFile{
		{
			Name:   globals.GCP_SECRETS_MODULE_NAME,
			Header: header,
			Body:   body,
		},
	}

	output := SecretsOutput{
		Table: tableFiles,
		Loot:  lootFiles,
	}

	// Write output using HandleOutputSmart with scope support
	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}
	err := internal.HandleOutputSmart(
		"gcp",
		m.Format,
		m.OutputDirectory,
		m.Verbosity,
		m.WrapTable,
		"project",    // scopeType
		m.ProjectIDs, // scopeIdentifiers
		scopeNames,   // scopeNames
		m.Account,
		output,
	)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_SECRETS_MODULE_NAME)
		m.CommandCounter.Error++
	}
}
