package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	spannerservice "github.com/BishopFox/cloudfox/gcp/services/spannerService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPSpannerCommand = &cobra.Command{
	Use:     globals.GCP_SPANNER_MODULE_NAME,
	Aliases: []string{"cloud-spanner"},
	Short:   "Enumerate Cloud Spanner instances and databases",
	Long: `Enumerate Cloud Spanner instances and databases with IAM bindings.

Features:
- Lists all Spanner instances with configuration details
- Shows databases within each instance with encryption info
- Enumerates IAM bindings at both instance and database levels
- Generates gcloud commands for further analysis`,
	Run: runGCPSpannerCommand,
}

type SpannerModule struct {
	gcpinternal.BaseGCPModule
	Instances []spannerservice.SpannerInstanceInfo
	Databases []spannerservice.SpannerDatabaseInfo
	LootMap   map[string]*internal.LootFile
	mu        sync.Mutex
}

type SpannerOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o SpannerOutput) TableFiles() []internal.TableFile { return o.Table }
func (o SpannerOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPSpannerCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_SPANNER_MODULE_NAME)
	if err != nil {
		return
	}

	module := &SpannerModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Instances:     []spannerservice.SpannerInstanceInfo{},
		Databases:     []spannerservice.SpannerDatabaseInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *SpannerModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_SPANNER_MODULE_NAME, m.processProject)

	if len(m.Instances) == 0 {
		logger.InfoM("No Spanner instances found", globals.GCP_SPANNER_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d Spanner instance(s) with %d database(s)",
		len(m.Instances), len(m.Databases)), globals.GCP_SPANNER_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *SpannerModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating Spanner in project: %s", projectID), globals.GCP_SPANNER_MODULE_NAME)
	}

	svc := spannerservice.New()
	result, err := svc.ListInstancesAndDatabases(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_SPANNER_MODULE_NAME,
			fmt.Sprintf("Could not list Spanner instances in project %s", projectID))
		return
	}

	m.mu.Lock()
	m.Instances = append(m.Instances, result.Instances...)
	m.Databases = append(m.Databases, result.Databases...)

	for _, instance := range result.Instances {
		m.addInstanceToLoot(instance)
	}
	for _, database := range result.Databases {
		m.addDatabaseToLoot(database)
	}
	m.mu.Unlock()

	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Found %d instance(s) and %d database(s) in project %s",
			len(result.Instances), len(result.Databases), projectID), globals.GCP_SPANNER_MODULE_NAME)
	}
}

func (m *SpannerModule) initializeLootFiles() {
	m.LootMap["spanner-commands"] = &internal.LootFile{
		Name:     "spanner-commands",
		Contents: "# Spanner Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
}

func (m *SpannerModule) addInstanceToLoot(instance spannerservice.SpannerInstanceInfo) {
	m.LootMap["spanner-commands"].Contents += fmt.Sprintf(
		"# ==========================================\n"+
			"# INSTANCE: %s\n"+
			"# ==========================================\n"+
			"# Project: %s\n"+
			"# Display Name: %s\n"+
			"# Config: %s\n"+
			"# Nodes: %d\n"+
			"# State: %s\n",
		instance.Name, instance.ProjectID,
		instance.DisplayName, instance.Config,
		instance.NodeCount, instance.State,
	)

	if len(instance.IAMBindings) > 0 {
		m.LootMap["spanner-commands"].Contents += "# IAM Bindings:\n"
		for _, binding := range instance.IAMBindings {
			m.LootMap["spanner-commands"].Contents += fmt.Sprintf("#   %s -> %s\n", binding.Role, binding.Member)
		}
	}

	m.LootMap["spanner-commands"].Contents += fmt.Sprintf(
		"\n# Describe instance:\n"+
			"gcloud spanner instances describe %s --project=%s\n\n"+
			"# List databases:\n"+
			"gcloud spanner databases list --instance=%s --project=%s\n\n"+
			"# Get IAM policy:\n"+
			"gcloud spanner instances get-iam-policy %s --project=%s\n\n",
		instance.Name, instance.ProjectID,
		instance.Name, instance.ProjectID,
		instance.Name, instance.ProjectID,
	)
}

func (m *SpannerModule) addDatabaseToLoot(database spannerservice.SpannerDatabaseInfo) {
	m.LootMap["spanner-commands"].Contents += fmt.Sprintf(
		"# ------------------------------------------\n"+
			"# DATABASE: %s (Instance: %s)\n"+
			"# ------------------------------------------\n"+
			"# Project: %s\n"+
			"# State: %s\n"+
			"# Encryption: %s\n",
		database.Name, database.InstanceName,
		database.ProjectID, database.State,
		database.EncryptionType,
	)

	if database.KmsKeyName != "" {
		m.LootMap["spanner-commands"].Contents += fmt.Sprintf("# KMS Key: %s\n", database.KmsKeyName)
	}

	if len(database.IAMBindings) > 0 {
		m.LootMap["spanner-commands"].Contents += "# IAM Bindings:\n"
		for _, binding := range database.IAMBindings {
			m.LootMap["spanner-commands"].Contents += fmt.Sprintf("#   %s -> %s\n", binding.Role, binding.Member)
		}
	}

	m.LootMap["spanner-commands"].Contents += fmt.Sprintf(
		"\n# Describe database:\n"+
			"gcloud spanner databases describe %s --instance=%s --project=%s\n\n"+
			"# Get database IAM policy:\n"+
			"gcloud spanner databases get-iam-policy %s --instance=%s --project=%s\n\n"+
			"# Execute SQL query:\n"+
			"gcloud spanner databases execute-sql %s --instance=%s --project=%s --sql=\"SELECT * FROM INFORMATION_SCHEMA.TABLES\"\n\n",
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
		database.Name, database.InstanceName, database.ProjectID,
	)
}

func (m *SpannerModule) writeOutput(ctx context.Context, logger internal.Logger) {
	// Instance table - one row per IAM binding
	instanceHeader := []string{
		"Project Name",
		"Project ID",
		"Instance",
		"Display Name",
		"Config",
		"Nodes",
		"State",
		"IAM Role",
		"IAM Member",
	}

	var instanceBody [][]string
	for _, instance := range m.Instances {
		if len(instance.IAMBindings) > 0 {
			for _, binding := range instance.IAMBindings {
				instanceBody = append(instanceBody, []string{
					m.GetProjectName(instance.ProjectID),
					instance.ProjectID,
					instance.Name,
					instance.DisplayName,
					instance.Config,
					fmt.Sprintf("%d", instance.NodeCount),
					instance.State,
					binding.Role,
					binding.Member,
				})
			}
		} else {
			// Instance with no IAM bindings
			instanceBody = append(instanceBody, []string{
				m.GetProjectName(instance.ProjectID),
				instance.ProjectID,
				instance.Name,
				instance.DisplayName,
				instance.Config,
				fmt.Sprintf("%d", instance.NodeCount),
				instance.State,
				"-",
				"-",
			})
		}
	}

	// Database table - one row per IAM binding
	databaseHeader := []string{
		"Project Name",
		"Project ID",
		"Instance",
		"Database",
		"State",
		"Encryption",
		"KMS Key",
		"IAM Role",
		"IAM Member",
	}

	var databaseBody [][]string
	for _, database := range m.Databases {
		kmsKey := "-"
		if database.KmsKeyName != "" {
			kmsKey = database.KmsKeyName
		}

		if len(database.IAMBindings) > 0 {
			for _, binding := range database.IAMBindings {
				databaseBody = append(databaseBody, []string{
					m.GetProjectName(database.ProjectID),
					database.ProjectID,
					database.InstanceName,
					database.Name,
					database.State,
					database.EncryptionType,
					kmsKey,
					binding.Role,
					binding.Member,
				})
			}
		} else {
			// Database with no IAM bindings
			databaseBody = append(databaseBody, []string{
				m.GetProjectName(database.ProjectID),
				database.ProjectID,
				database.InstanceName,
				database.Name,
				database.State,
				database.EncryptionType,
				kmsKey,
				"-",
				"-",
			})
		}
	}

	// Collect loot files
	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	// Build tables
	tables := []internal.TableFile{
		{
			Name:   "spanner-instances",
			Header: instanceHeader,
			Body:   instanceBody,
		},
	}

	if len(databaseBody) > 0 {
		tables = append(tables, internal.TableFile{
			Name:   "spanner-databases",
			Header: databaseHeader,
			Body:   databaseBody,
		})
	}

	output := SpannerOutput{
		Table: tables,
		Loot:  lootFiles,
	}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_SPANNER_MODULE_NAME)
		m.CommandCounter.Error++
	}
}
