package commands

import (
	"context"
	"fmt"
	"strings"
	"sync"

	vpcservice "github.com/BishopFox/cloudfox/gcp/services/vpcService"
	"github.com/BishopFox/cloudfox/globals"
	"github.com/BishopFox/cloudfox/internal"
	gcpinternal "github.com/BishopFox/cloudfox/internal/gcp"
	"github.com/spf13/cobra"
)

var GCPVPCNetworksCommand = &cobra.Command{
	Use:     globals.GCP_VPCNETWORKS_MODULE_NAME,
	Aliases: []string{"vpc", "networks", "net"},
	Short:   "Enumerate VPC Networks",
	Long: `Enumerate VPC Networks and related configurations.

Features:
- Lists all VPC networks and subnets
- Shows VPC peering connections
- Analyzes routing tables
- Checks for Private Google Access
- Identifies flow log configuration`,
	Run: runGCPVPCNetworksCommand,
}

type VPCNetworksModule struct {
	gcpinternal.BaseGCPModule
	Networks []vpcservice.VPCNetworkInfo
	Subnets  []vpcservice.SubnetInfo
	Peerings []vpcservice.VPCPeeringInfo
	Routes   []vpcservice.RouteInfo
	LootMap  map[string]*internal.LootFile
	mu       sync.Mutex
}

type VPCNetworksOutput struct {
	Table []internal.TableFile
	Loot  []internal.LootFile
}

func (o VPCNetworksOutput) TableFiles() []internal.TableFile { return o.Table }
func (o VPCNetworksOutput) LootFiles() []internal.LootFile   { return o.Loot }

func runGCPVPCNetworksCommand(cmd *cobra.Command, args []string) {
	cmdCtx, err := gcpinternal.InitializeCommandContext(cmd, globals.GCP_VPCNETWORKS_MODULE_NAME)
	if err != nil {
		return
	}

	module := &VPCNetworksModule{
		BaseGCPModule: gcpinternal.NewBaseGCPModule(cmdCtx),
		Networks:      []vpcservice.VPCNetworkInfo{},
		Subnets:       []vpcservice.SubnetInfo{},
		Peerings:      []vpcservice.VPCPeeringInfo{},
		Routes:        []vpcservice.RouteInfo{},
		LootMap:       make(map[string]*internal.LootFile),
	}
	module.initializeLootFiles()
	module.Execute(cmdCtx.Ctx, cmdCtx.Logger)
}

func (m *VPCNetworksModule) Execute(ctx context.Context, logger internal.Logger) {
	m.RunProjectEnumeration(ctx, logger, m.ProjectIDs, globals.GCP_VPCNETWORKS_MODULE_NAME, m.processProject)

	if len(m.Networks) == 0 {
		logger.InfoM("No VPC networks found", globals.GCP_VPCNETWORKS_MODULE_NAME)
		return
	}

	logger.SuccessM(fmt.Sprintf("Found %d VPC network(s), %d subnet(s), %d peering(s), %d route(s)",
		len(m.Networks), len(m.Subnets), len(m.Peerings), len(m.Routes)), globals.GCP_VPCNETWORKS_MODULE_NAME)
	m.writeOutput(ctx, logger)
}

func (m *VPCNetworksModule) processProject(ctx context.Context, projectID string, logger internal.Logger) {
	if globals.GCP_VERBOSITY >= globals.GCP_VERBOSE_ERRORS {
		logger.InfoM(fmt.Sprintf("Enumerating VPC networks in project: %s", projectID), globals.GCP_VPCNETWORKS_MODULE_NAME)
	}

	svc := vpcservice.New()

	// Get networks
	networks, err := svc.ListVPCNetworks(projectID)
	if err != nil {
		m.CommandCounter.Error++
		gcpinternal.HandleGCPError(err, logger, globals.GCP_VPCNETWORKS_MODULE_NAME,
			fmt.Sprintf("Could not list VPC networks in project %s", projectID))
	} else {
		m.mu.Lock()
		m.Networks = append(m.Networks, networks...)
		m.mu.Unlock()
	}

	// Get subnets
	subnets, err := svc.ListSubnets(projectID)
	if err == nil {
		m.mu.Lock()
		m.Subnets = append(m.Subnets, subnets...)
		m.mu.Unlock()
	}

	// Get peerings
	peerings, err := svc.ListVPCPeerings(projectID)
	if err == nil {
		m.mu.Lock()
		m.Peerings = append(m.Peerings, peerings...)
		m.mu.Unlock()
	}

	// Get routes
	routes, err := svc.ListRoutes(projectID)
	if err == nil {
		m.mu.Lock()
		m.Routes = append(m.Routes, routes...)
		m.mu.Unlock()
	}

	m.mu.Lock()
	for _, network := range networks {
		m.addNetworkToLoot(network)
	}
	for _, subnet := range subnets {
		m.addSubnetToLoot(subnet)
	}
	for _, peering := range peerings {
		m.addPeeringToLoot(peering)
	}
	m.mu.Unlock()
}

func (m *VPCNetworksModule) initializeLootFiles() {
	m.LootMap["vpcnetworks-commands"] = &internal.LootFile{
		Name:     "vpcnetworks-commands",
		Contents: "# VPC Networks Commands\n# Generated by CloudFox\n# WARNING: Only use with proper authorization\n\n",
	}
}

func (m *VPCNetworksModule) addNetworkToLoot(network vpcservice.VPCNetworkInfo) {
	m.LootMap["vpcnetworks-commands"].Contents += fmt.Sprintf(
		"# ==========================================\n"+
			"# NETWORK: %s\n"+
			"# ==========================================\n"+
			"# Project: %s\n"+
			"# Routing Mode: %s\n"+
			"# Auto Create Subnets: %v\n"+
			"# Subnets: %d\n"+
			"# Peerings: %d\n"+
			"\n# Describe network:\n"+
			"gcloud compute networks describe %s --project=%s\n\n"+
			"# List subnets in network:\n"+
			"gcloud compute networks subnets list --network=%s --project=%s\n\n"+
			"# List peerings:\n"+
			"gcloud compute networks peerings list --network=%s --project=%s\n\n",
		network.Name,
		network.ProjectID,
		network.RoutingMode,
		network.AutoCreateSubnetworks,
		len(network.Subnetworks),
		len(network.Peerings),
		network.Name, network.ProjectID,
		network.Name, network.ProjectID,
		network.Name, network.ProjectID,
	)
}

func (m *VPCNetworksModule) addSubnetToLoot(subnet vpcservice.SubnetInfo) {
	m.LootMap["vpcnetworks-commands"].Contents += fmt.Sprintf(
		"# ------------------------------------------\n"+
			"# SUBNET: %s (Network: %s)\n"+
			"# ------------------------------------------\n"+
			"# Project: %s\n"+
			"# Region: %s\n"+
			"# CIDR: %s\n"+
			"# Private Google Access: %v\n"+
			"# Flow Logs: %v\n"+
			"\n# Describe subnet:\n"+
			"gcloud compute networks subnets describe %s --region=%s --project=%s\n\n",
		subnet.Name, subnet.Network,
		subnet.ProjectID,
		subnet.Region,
		subnet.IPCidrRange,
		subnet.PrivateIPGoogleAccess,
		subnet.EnableFlowLogs,
		subnet.Name, subnet.Region, subnet.ProjectID,
	)
}

func (m *VPCNetworksModule) addPeeringToLoot(peering vpcservice.VPCPeeringInfo) {
	m.LootMap["vpcnetworks-commands"].Contents += fmt.Sprintf(
		"# ------------------------------------------\n"+
			"# PEERING: %s\n"+
			"# ------------------------------------------\n"+
			"# Project: %s\n"+
			"# Network: %s -> Peer Network: %s\n"+
			"# Peer Project: %s\n"+
			"# State: %s\n"+
			"# Export Routes: %v, Import Routes: %v\n",
		peering.Name,
		peering.ProjectID,
		peering.Network, peering.PeerNetwork,
		peering.PeerProjectID,
		peering.State,
		peering.ExportCustomRoutes, peering.ImportCustomRoutes,
	)

	// Cross-project peering commands
	if peering.PeerProjectID != "" && peering.PeerProjectID != peering.ProjectID {
		m.LootMap["vpcnetworks-commands"].Contents += fmt.Sprintf(
			"\n# Cross-project peering - enumerate peer project:\n"+
				"gcloud compute instances list --project=%s\n"+
				"gcloud compute networks subnets list --project=%s\n\n",
			peering.PeerProjectID,
			peering.PeerProjectID,
		)
	} else {
		m.LootMap["vpcnetworks-commands"].Contents += "\n"
	}
}

func (m *VPCNetworksModule) writeOutput(ctx context.Context, logger internal.Logger) {
	var tables []internal.TableFile

	// Networks table
	netHeader := []string{"Project Name", "Project ID", "Name", "Routing Mode", "Auto Subnets", "Subnets", "Peerings"}
	var netBody [][]string
	for _, network := range m.Networks {
		autoSubnets := "No"
		if network.AutoCreateSubnetworks {
			autoSubnets = "Yes"
		}
		netBody = append(netBody, []string{
			m.GetProjectName(network.ProjectID),
			network.ProjectID,
			network.Name,
			network.RoutingMode,
			autoSubnets,
			fmt.Sprintf("%d", len(network.Subnetworks)),
			fmt.Sprintf("%d", len(network.Peerings)),
		})
	}
	tables = append(tables, internal.TableFile{
		Name:   "vpc-networks",
		Header: netHeader,
		Body:   netBody,
	})

	// Subnets table
	if len(m.Subnets) > 0 {
		subHeader := []string{"Project Name", "Project ID", "Name", "Network", "Region", "CIDR", "Private Access", "Flow Logs"}
		var subBody [][]string
		for _, subnet := range m.Subnets {
			privateAccess := "No"
			if subnet.PrivateIPGoogleAccess {
				privateAccess = "Yes"
			}
			flowLogs := "No"
			if subnet.EnableFlowLogs {
				flowLogs = "Yes"
			}
			subBody = append(subBody, []string{
				m.GetProjectName(subnet.ProjectID),
				subnet.ProjectID,
				subnet.Name,
				subnet.Network,
				subnet.Region,
				subnet.IPCidrRange,
				privateAccess,
				flowLogs,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "subnets",
			Header: subHeader,
			Body:   subBody,
		})
	}

	// Peerings table
	if len(m.Peerings) > 0 {
		peerHeader := []string{"Project Name", "Project ID", "Name", "Network", "Peer Network", "Peer Project", "State", "Export Routes", "Import Routes"}
		var peerBody [][]string
		for _, peering := range m.Peerings {
			peerProject := peering.PeerProjectID
			if peerProject == "" {
				peerProject = "-"
			}
			exportRoutes := "No"
			if peering.ExportCustomRoutes {
				exportRoutes = "Yes"
			}
			importRoutes := "No"
			if peering.ImportCustomRoutes {
				importRoutes = "Yes"
			}
			peerBody = append(peerBody, []string{
				m.GetProjectName(peering.ProjectID),
				peering.ProjectID,
				peering.Name,
				peering.Network,
				peering.PeerNetwork,
				peerProject,
				peering.State,
				exportRoutes,
				importRoutes,
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "vpc-peerings",
			Header: peerHeader,
			Body:   peerBody,
		})
	}

	// Routes table (custom routes only, skip default)
	var customRoutes []vpcservice.RouteInfo
	for _, route := range m.Routes {
		if !strings.HasPrefix(route.Name, "default-route-") {
			customRoutes = append(customRoutes, route)
		}
	}
	if len(customRoutes) > 0 {
		routeHeader := []string{"Project Name", "Project ID", "Name", "Network", "Dest Range", "Next Hop Type", "Next Hop", "Priority"}
		var routeBody [][]string
		for _, route := range customRoutes {
			routeBody = append(routeBody, []string{
				m.GetProjectName(route.ProjectID),
				route.ProjectID,
				route.Name,
				route.Network,
				route.DestRange,
				route.NextHopType,
				route.NextHop,
				fmt.Sprintf("%d", route.Priority),
			})
		}
		tables = append(tables, internal.TableFile{
			Name:   "custom-routes",
			Header: routeHeader,
			Body:   routeBody,
		})
	}

	var lootFiles []internal.LootFile
	for _, loot := range m.LootMap {
		if loot.Contents != "" && !strings.HasSuffix(loot.Contents, "# WARNING: Only use with proper authorization\n\n") {
			lootFiles = append(lootFiles, *loot)
		}
	}

	output := VPCNetworksOutput{Table: tables, Loot: lootFiles}

	scopeNames := make([]string, len(m.ProjectIDs))
	for i, id := range m.ProjectIDs {
		scopeNames[i] = m.GetProjectName(id)
	}

	err := internal.HandleOutputSmart("gcp", m.Format, m.OutputDirectory, m.Verbosity, m.WrapTable,
		"project", m.ProjectIDs, scopeNames, m.Account, output)
	if err != nil {
		logger.ErrorM(fmt.Sprintf("Error writing output: %v", err), globals.GCP_VPCNETWORKS_MODULE_NAME)
	}
}
